use ods_enterprise;
drop table if exists g05_enterprise_tel_ul_tx_ck;
drop table if exists g05_new_ck_kafka_enterprise_tel_ul_tx;
create table g05_enterprise_tel_ul_tx_ck
(
    id                               String,
    message_time                     Timestamp,
    vehiclemodelcode                 String,
    vin String,
    vin_mask String,
    message_type String,
    ACU_AEBOff	Bigint  comment ' 默认值-99999 AEB is turned off',
    ACU_AVHSoftSwitchst	Bigint  comment ' 默认值-99999 Indication the AVHSoftSwitch  status',
    ACU_CurrentSource	Bigint  comment ' 默认值-99999 ACU Current source',
    ACU_DragModeReq	Bigint  comment ' 默认值-99999 ACU Drag Mode Reqest Status',
    ACU_EPBSwitchSt	Bigint  comment ' 默认值-99999 Indication the EPBswitch status',
    ACU_EPSStyleCfg	Bigint  comment ' 默认值-99999 Configurates the style of EPS',
    ACU_FCWOff	Bigint  comment ' 默认值-99999 FCW is turned off',
    ACU_FCWWarnDistanceCfg	Bigint  comment ' 默认值-99999 Configurates FCW(Front Collision Warning) warning distance',
    ACU_HMA_SwitchReq	Bigint  comment ' 默认值-99999 HMA(High Beam Assistant) switch signal',
    ACU_iACC_SwitchReq	Bigint  comment ' 默认值-99999 iACC(TSR information fusion with ACC) switch signal',
    ACU_IFC_ISDRestOfdis	DECIMAL(18, 8)  comment ' 默认值-99999 Interval speed detection rest of distacne. Once navigation jduge vehicle run in an interval speed detection area of road, this signal begin to send specific value, otherwise keep sending 0x0.',
    ACU_IFC_NaviCorp	Bigint  comment ' 默认值-99999 the working navigation map corporation',
    ACU_IFC_NaviNewIcon	Bigint  comment ' 默认值-99999 indication the navigation newIcon',
    ACU_IFC_NaviNewIconDis	DECIMAL(18, 8)  comment ' 默认值-99999 the remain distances of navigation newIcon',
    ACU_IFC_NaviSt	Bigint  comment ' 默认值-99999 Navigation state',
    ACU_IFC_OfframpDis	Bigint  comment ' 默认值-99999 The distance to front off-ramp',
    ACU_IFC_OfframpSt	Bigint  comment ' 默认值-99999 The front is off-ramp or not when navigation',
    ACU_IFC_RoadType	Bigint  comment ' 默认值-99999 Road type from navigation map data and GPS location.',
    ACU_IFC_SLCAheadDis	Bigint  comment ' 默认值-99999 speed limit camera ahead distacne. Once navigation jduge there is a speed limit camera ahead that the vehicle will pass by, this signal begin to send specific value, otherwise keep sending 0x0.',
    ACU_IFC_SpeedLimit	Bigint  comment ' 默认值-99999 Speed limit value from navigation map data and GPS location.',
    ACU_IFC_SpeedLimtType	Bigint  comment ' 默认值-99999 speed limit type from navigation map data and GPS location.',
    ACU_Latitude	Bigint  comment ' 默认值-99999 Latitude',
    ACU_LDW_LKACfg	Bigint  comment ' 默认值-99999 Configurates LDW lane keeping assist',
    ACU_LKS_TypeReq	Bigint  comment ' 默认值-99999 LKS(Lane Keeping Support) lane aid type request',
    ACU_Longitude	Bigint  comment ' 默认值-99999 Longitude',
    ACU_TSR_AudioWarnReq	Bigint  comment ' 默认值-99999 TSR(Traffic Sign Recognition) audio warning on off signal',
    ACU_TSR_SwitchReq	Bigint  comment ' 默认值-99999 TSR(Traffic Sign Recognition) switch signal',
    ADAS_AdjLLnMrkingDispSt	Bigint  comment ' 默认值-99999 Display state of Left adjacent Lanes Left Lane Marking',
    ADAS_AdjRLnMrkingDispSt	Bigint  comment ' 默认值-99999 Display state of Right adjacent Lanes Right Lane Marking',
    ADAS_LLnMarkingDisPropToLnWidth	Bigint  comment ' 默认值-99999 The proportion of left lane marking distance to the lane width.It also stands for The lane markings position to the middle of the ego vehicle for HMI display. 0% means the point the middle of ego vehicle cross left lane marking while 100% means crossing the right one.',
    ADAS_LLnMarkingType	Bigint  comment ' 默认值-99999 Left side of lane marking indication type',
    ADAS_LlnMrkingDispSt	Bigint  comment ' 默认值-99999 Display state of the left lane marking',
    ADAS_LLnMrkingPolyCoeffA0	DECIMAL(18, 8)  comment ' 默认值-99999 Left Lane Marking Polynomial Coefficient A0, which stands for the lateral distance between lane marking and the middle of the eog vehicle.',
    ADAS_LLnMrkingPolyCoeffA1	DECIMAL(18, 8)  comment ' 默认值-99999 Left Lane Marking Polynomial Coefficient A1, which stands for the heading angle between the lane marking and the ego vehicle.',
    ADAS_LLnMrkingPolyCoeffA2	DECIMAL(18, 8)  comment ' 默认值-99999 Left Lane Marking Polynomial Coefficient A2, which stands for the curvature of the lane marking.',
    ADAS_LnMarkingCurvature	DECIMAL(18, 8)  comment ' 默认值-99999 The curvature of the lane markings for HMI display.',
    ADAS_LnMarkingHeadAngToVeh	DECIMAL(18, 8)  comment ' 默认值-99999 The heading angle between lane markings and ego vehicle for HMI display.',
    ADAS_RLnMarkingType	Bigint  comment ' 默认值-99999 Right side of lane marking indication type',
    ADAS_RlnMrkingDispSt	Bigint  comment ' 默认值-99999 Display state of the right lane marking',
    ADAS_RLnMrkingPolyCoeffA0	DECIMAL(18, 8)  comment ' 默认值-99999 Right Lane Marking Polynomial Coefficient A0, which stands for the lateral distance between the lane marking and the middle of the eog vehicle.',
    ADAS_RLnMrkingPolyCoeffA1	DECIMAL(18, 8)  comment ' 默认值-99999 Right Lane Marking Polynomial Coefficient A1, which stands for the heading angle between the lane marking and the ego vehicle.',
    ADAS_RLnMrkingPolyCoeffA2	DECIMAL(18, 8)  comment ' 默认值-99999 Right Lane Marking Polynomial Coefficient A2, which stands for the curvature of the lane marking.',
    ADAS_TrkTargt0latPos	DECIMAL(18, 8)  comment ' 默认值-99999 Track Target 0（Closest Same Lane） Lateral Position',
    ADAS_TrkTargt0longPos	Bigint  comment ' 默认值-99999 Track Target 0（Closest Same Lane） Longitudinal Position',
    ADAS_TrkTargt0ObjClass	Bigint  comment ' 默认值-99999 Track Target 0（Closest Same Lane） Object class',
    ADAS_TrkTargt0St	Bigint  comment ' 默认值-99999 Track Target 0（Closest Same Lane） detection state',
    ADAS_TrkTargt1latPos	DECIMAL(18, 8)  comment ' 默认值-99999 Track Target 1（Before Tarcet 0, The Second Closest Same Lane） Lateral Position',
    ADAS_TrkTargt1longPos	Bigint  comment ' 默认值-99999 Track Target 1（Before Tarcet 0, TheSecond Closest Same Lane） Longitudinal Position',
    ADAS_TrkTargt1ObjClass	Bigint  comment ' 默认值-99999 Track Target 1（Before Tarcet 0, The Second Closest Same Lane）Object class',
    ADAS_TrkTargt1St	Bigint  comment ' 默认值-99999 Track Target 1（Before Tarcet 0, TheSecond Closest Same Lane）detection state',
    ADAS_TrkTargt2latPos	DECIMAL(18, 8)  comment ' 默认值-99999 Track Target 2（Closest Left Lane） Lateral Position',
    ADAS_TrkTargt2longPos	Bigint  comment ' 默认值-99999 Track Target 2（Closest Left Lane） Longitudinal Position',
    ADAS_TrkTargt2ObjClass	Bigint  comment ' 默认值-99999 Track Target 2（Closest Left Lane）Object class',
    ADAS_TrkTargt2St	Bigint  comment ' 默认值-99999 Track Target 2（Closest Left Lane） detection state',
    ADAS_TrkTargt3latPos	DECIMAL(18, 8)  comment ' 默认值-99999 Track Target 3（Closest Right Lane） Lateral Position',
    ADAS_TrkTargt3longPos	Bigint  comment ' 默认值-99999 Track Target 3（Closest Right Lane） Longitudinal Position',
    ADAS_TrkTargt3ObjClass	Bigint  comment ' 默认值-99999 Track Target 3（Closest Right Lane） Object class',
    ADAS_TrkTargt3St	Bigint  comment ' 默认值-99999 Track Target 3（Closest Right Lane） detection state',
    BCM_AlarmHistory	Bigint  comment ' 默认值-99999 BCM recent alarm trigger reason',
    BCM_ATWS_St	Bigint  comment ' 默认值-99999 Anti-theft warning status',
    BCM_AutoLightCtrlSt	Bigint  comment ' 默认值-99999 Auto light control by IFC(Intelligent FrontCamera)status',
    BCM_AutoLightSnsCfgSt	Bigint  comment ' 默认值-99999 Sensibility of auto light configuration status',
    BCM_AutoUnlockCfgSt	Bigint  comment ' 默认值-99999 Auto unlock doors configuration status',
    BCM_BeamSwitchSt	Bigint  comment ' 默认值-99999 Beam switch status',
    BCM_BonnetAjarSt	Bigint  comment ' 默认值-99999 Bonnet/hood ajar status',
    BCM_BonnetAjarSt_Change	Bigint  comment ' 默认值-99999 nan',
    BCM_BrakeLightFaultSt	Bigint  comment ' 默认值-99999 Brake light fault status',
    BCM_BrakeLightSt	Bigint  comment ' 默认值-99999 Brake light status',
    BCM_BrakeLightSwitchSt	Bigint  comment ' 默认值-99999 Brake light switch status',
    BCM_CentralLockSWSt	Bigint  comment ' 默认值-99999 Central lock switch status',
    BCM_DriverDoorAjarSt	Bigint  comment ' 默认值-99999 Driver door ajar status',
    BCM_DriverDoorAjarSt_Change	Bigint  comment ' 默认值-99999 nan',
    BCM_DriverDoorLockSt	Bigint  comment ' 默认值-99999 Driver door lock status',
    BCM_DriverDoorLockSt_Change	Bigint  comment ' 默认值-99999 nan',
    BCM_DRLLFaultSt	Bigint  comment ' 默认值-99999 Left side DRL(Daytime Running Lamp) fault status',
    BCM_DRLRFaultSt	Bigint  comment ' 默认值-99999 Right side DRL(Daytime Running Lamp) fault status',
    BCM_DTRLFuncCfgSt	Bigint  comment ' 默认值-99999 BCM day time running lamp function configurationstatus',
    BCM_DTRLSt	Bigint  comment ' 默认值-99999 Day time running lamp status',
    BCM_ETWS_St	Bigint  comment ' 默认值-99999 Engine theft warning status',
    BCM_FLWinSt	Bigint  comment ' 默认值-99999 Front left window status',
    BCM_FLWinSt_Change	Bigint  comment ' 默认值-99999 nan',
    BCM_FOB_ID	Bigint  comment ' 默认值-99999 Fob identification',
    BCM_FogLampTurnCfgSt	Bigint  comment ' 默认值-99999 Fog lamp auxiliary lighting when turningconfiguration status',
    BCM_FrontFogLampSt	Bigint  comment ' 默认值-99999 Front fog lamp status',
    BCM_FrontFogLampSt_Change	Bigint  comment ' 默认值-99999 nan',
    BCM_FrontWasherSt	Bigint  comment ' 默认值-99999 Front washer status',
    BCM_FrontWasherSt_Change	Bigint  comment ' 默认值-99999 nan',
    BCM_FrontWiperSt	Bigint  comment ' 默认值-99999 Front wiper status',
    BCM_FRWinSt	Bigint  comment ' 默认值-99999 Front rear window status',
    BCM_FRWinSt_Change	Bigint  comment ' 默认值-99999 nan',
    BCM_HazardLampSt	Bigint  comment ' 默认值-99999 Hazard lamp status',
    BCM_HighBeamSt	Bigint  comment ' 默认值-99999 High beam status',
    BCM_IGNOffTime	Bigint  comment ' 默认值-99999 Ignition off time',
    BCM_KeyInReminderWarnReq	Bigint  comment ' 默认值-99999 Key in reminder warning',
    BCM_KeySt	Bigint  comment ' 默认值-99999 Ignition key position status',
    BCM_LampOnWarningReq	Bigint  comment ' 默认值-99999 Lamp left on warning request',
    BCM_LeftTurnLampFaultSt	Bigint  comment ' 默认值-99999 Left turn lamp fault status',
    BCM_LeftTurnLampSt	Bigint  comment ' 默认值-99999 Left turn lamp status',
    BCM_LeftTurnLampSt_Change	Bigint  comment ' 默认值-99999 nan',
    BCM_LowBeamSt	Bigint  comment ' 默认值-99999 Low beam status',
    BCM_ParkingLampSt	Bigint  comment ' 默认值-99999 Parking lamp status',
    BCM_ParkingLampSt_Change	Bigint  comment ' 默认值-99999 nan',
    BCM_PowerWinOpenWarn	Bigint  comment ' 默认值-99999 Windows open warning',
    BCM_PsngrDoorAjarSt	Bigint  comment ' 默认值-99999 Passenger door ajar status',
    BCM_PsngrDoorAjarSt_Change	Bigint  comment ' 默认值-99999 nan',
    BCM_PsngrDoorLockSt	Bigint  comment ' 默认值-99999 Passenger door lock status',
    BCM_PsngrDoorLockSt_Change	Bigint  comment ' 默认值-99999 nan',
    BCM_RearFogLampSt	Bigint  comment ' 默认值-99999 Rear fog lamp status',
    BCM_RearFogLampSt_Change	Bigint  comment ' 默认值-99999 nan',
    BCM_RemoteControlSt	Bigint  comment ' 默认值-99999 BCM leave out remote mode reasons',
    BCM_ReverseLightSt	Bigint  comment ' 默认值-99999 Reverse light status',
    BCM_ReverseSwitchSt	Bigint  comment ' 默认值-99999 Reverse switch status',
    BCM_RightTurnLampFaultSt	Bigint  comment ' 默认值-99999 Right turn lamp fault status',
    BCM_RightTurnLampSt	Bigint  comment ' 默认值-99999 Right turn lamp status',
    BCM_RightTurnLampSt_Change	Bigint  comment ' 默认值-99999 nan',
    BCM_RLDoorAjarSt	Bigint  comment ' 默认值-99999 Rear left door ajar status',
    BCM_RLDoorAjarSt_Change	Bigint  comment ' 默认值-99999 nan',
    BCM_RLSWarning_Light	Bigint  comment ' 默认值-99999 RLS auto light warning',
    BCM_RLSWarning_Rain	Bigint  comment ' 默认值-99999 RLS auto wiper warning',
    BCM_RLWinSt	Bigint  comment ' 默认值-99999 Rear left window status',
    BCM_RLWinSt_Change	Bigint  comment ' 默认值-99999 nan',
    BCM_RmtCtrlFobBattLow	Bigint  comment ' 默认值-99999 Remote control fob battery low',
    BCM_RoomlampSt	Bigint  comment ' 默认值-99999 Room lamp status',
    BCM_RRDoorAjarSt	Bigint  comment ' 默认值-99999 Rear right door ajar status',
    BCM_RRDoorAjarSt_Change	Bigint  comment ' 默认值-99999 nan',
    BCM_RRWinSt	Bigint  comment ' 默认值-99999 Rear right window status',
    BCM_RRWinSt_Change	Bigint  comment ' 默认值-99999 nan',
    BCM_SpdAutoLockCfgSt	Bigint  comment ' 默认值-99999 High speed auto lock doors configuration status',
    BCM_SunRoofOpenWarning	Bigint  comment ' 默认值-99999 SunRoof open warning',
    BCM_SunRoofPstSt	Bigint  comment ' 默认值-99999 The sun roof position status.',
    BCM_SunRoofPstSt_Change	Bigint  comment ' 默认值-99999 nan',
    BCM_TransportModeSt	Bigint  comment ' 默认值-99999 Transport mode status',
    BCM_TrunkAjarSt	Bigint  comment ' 默认值-99999 Trunk ajar status',
    BCM_TrunkAjarSt_Change	Bigint  comment ' 默认值-99999 nan',
    BCM_TurnLightSwitchSt	Bigint  comment ' 默认值-99999 Turn light switch status',
    BCM_VehReverseSt	Bigint  comment ' 默认值-99999 Indication the BCM judgement of the vehicle reversestatus',
    BCM_WinMoveSt	Bigint  comment ' 默认值-99999 Window move Status',
    BCS_ABAactive	Bigint  comment ' 默认值-99999 ABA(Adaptive Brake Assistance) is active',
    BCS_ABAavailable	Bigint  comment ' 默认值-99999 The ABA(Adaptive Brake Assistance)  function isavailable',
    BCS_ABPActive	Bigint  comment ' 默认值-99999 ABP(Automatic brake Pre-fill) is active',
    BCS_ABPAvailable	Bigint  comment ' 默认值-99999 ABP(Automatic brake Pre-fill) is available',
    BCS_ABSActiveSt	Bigint  comment ' 默认值-99999 Indication that ABS system currently performs abrake intervention',
    BCS_ABSFaultSt	Bigint  comment ' 默认值-99999 ABS system has detected a failure which does no allow a reliable ABS regulation and is thereforeswitched off',
    BCS_ActVehLaltrlAccel	DECIMAL(18, 8)  comment ' 默认值-99999 Actual vehicle lateral acceleration',
    BCS_ActVehLaltrlAccelVD	Bigint  comment ' 默认值-99999 Quality/fault information to actual vehicle lateralacceleration',
    BCS_ActVehLongAccel	DECIMAL(18, 8)  comment ' 默认值-99999 Actual vehicle longitudinal acceleration',
    BCS_ActVehLongAccelVD	Bigint  comment ' 默认值-99999 Quality/fault information to actual vehicle longitudinalacceleration',
    BCS_AEBActive	Bigint  comment ' 默认值-99999 AEB(Automatic EmergencyBraking) is active (in deceleration)',
    BCS_AEBAvailable	Bigint  comment ' 默认值-99999 AEB(Automatic EmergencyBraking) is available',
    BCS_APAGrarLvlReq	Bigint  comment ' 默认值-99999 Gear lever position request for the vehicle mo-tion control',
    BCS_APAGrarLvlReqVD	Bigint  comment ' 默认值-99999 enable flag to control the gear box',
    BCS_APALongContrAvail	Bigint  comment ' 默认值-99999 Indicate the function availability',
    BCS_APALongContrFailSt	Bigint  comment ' 默认值-99999 Indicate the failure of the longitudinal controller',
    BCS_APALongContrSt	Bigint  comment ' 默认值-99999 Longitudinal controller status',
    BCS_APATorqReqEV	Bigint  comment ' 默认值-99999 APA torque requst for EV',
    BCS_APATorqReqSt	Bigint  comment ' 默认值-99999 APA torque requst flag',
    BCS_AVHAvailable	Bigint  comment ' 默认值-99999 HMI responsible, can get degrate AVH(Auto VehicleHold) statement from DSW and send out',
    BCS_AVHSoftSwctrlst	Bigint  comment ' 默认值-99999 Feedback  AVH Soft Switch contral  status to ACU',
    BCS_AVHSt	Bigint  comment ' 默认值-99999 Indicates AVH(Auto Vehicle Hold)in active or not',
    BCS_AVHStandby	Bigint  comment ' 默认值-99999 Indicates AVH(Auto Vehicle Hold)in standby modeor not',
    BCS_AVHSwitchSt	Bigint  comment ' 默认值-99999 Status request information of AVH interaction',
    BCS_AWBActive	Bigint  comment ' 默认值-99999 AWB(Automatic Warning Brake) is active',
    BCS_AWBAvailable	Bigint  comment ' 默认值-99999 AWB(Automatic Warning Brake) is available',
    BCS_BrakeOverHeat	Bigint  comment ' 默认值-99999 Indicating brake temperature too high or not',
    BCS_CDDActive	Bigint  comment ' 默认值-99999 CDD(Controlled Deceleration for Driver) is active',
    BCS_CDDAvailable	Bigint  comment ' 默认值-99999 CDD(Controlled Deceleration for Driver) is available',
    BCS_CDDFail	Bigint  comment ' 默认值-99999 CDD in failure',
    BCS_CDPAvailable	Bigint  comment ' 默认值-99999 CDP(Controlled Deceleration for Parking brake)interface available',
    BCS_CDPIntervention	Bigint  comment ' 默认值-99999 CDP(Controlled Deceleration for Parking brake)intervention',
    BCS_CrbsActive	Bigint  comment ' 默认值-99999 Indicate whether ESP recuperation torque iscontrolled by CRBS',
    BCS_EBDActiveSt	Bigint  comment ' 默认值-99999 Indication that EBD system currently performs abrake/engine intervention',
    BCS_EBDFaultSt	Bigint  comment ' 默认值-99999 ABS system has detected a heavy fault, which does not even allow a reliable electronic brake distributionand is therefore completely shut down',
    BCS_EngTorqDecFastFA	DECIMAL(18, 8)  comment ' 默认值-99999 This torque  is engine combustion（indicated） decreased target torque (fast),applies to 4WD and front wheel drive',
    BCS_EngTorqInc	Bigint  comment ' 默认值-99999 This torque  is  increased engine combustion（indicated）target torque',
    BCS_EPBDragMode	Bigint  comment ' 默认值-99999 Drag Mode status',
    BCS_ESPFuncResp	Bigint  comment ' 默认值-99999 Response the ESP function status',
    BCS_ExterBrkReqTargetVolFlow	Bigint  comment ' 默认值-99999 Target volume flow for external brake request (EBR) by EBB',
    BCS_FLWheelRotatedDirection	Bigint  comment ' 默认值-99999 FL wheel rotate direction',
    BCS_FLWheelRotatedDirectionAPA	Bigint  comment ' 默认值-99999 FL wheel rotate direction for APA',
    BCS_FLWheelRotatedDirectionVD	Bigint  comment ' 默认值-99999 FL wheel rotate direction validity',
    BCS_FLWheelSpd	DECIMAL(18, 8)  comment ' 默认值-99999 Current wheel speed information of front left wheel',
    BCS_FLWheelSpdVD	Bigint  comment ' 默认值-99999 Quality/fault information to current wheel speed of front left wheel,be used for validity of BCS_FLWheelSpd and BCS_FLWheelSpdEdgesSum signal',
    BCS_FRWheelRotatedDirection	Bigint  comment ' 默认值-99999 FR wheel rotate direction',
    BCS_FRWheelRotatedDirectionAPA	Bigint  comment ' 默认值-99999 FR wheel rotate direction for APA',
    BCS_FRWheelRotatedDirectionVD	Bigint  comment ' 默认值-99999 FR wheel rotate direction validity',
    BCS_FRWheelSpd	DECIMAL(18, 8)  comment ' 默认值-99999 Current wheel speed information of front right wheel',
    BCS_FRWheelSpdVD	Bigint  comment ' 默认值-99999 Quality/fault information to current wheel speed of front left wheel,be used for validity of BCS_FRWheelSpd and BCS_FRWheelSpdEdgesSum signal',
    BCS_HBBIntervention	Bigint  comment ' 默认值-99999 This signal indicates if HBB is active or not',
    BCS_HBBStatus	Bigint  comment ' 默认值-99999 This signal indicates the status of HBB',
    BCS_HDCCtrlSt	Bigint  comment ' 默认值-99999 HDC(Hill Descent Control) Control status',
    BCS_HDCErrSt	Bigint  comment ' 默认值-99999 HDC error Status',
    BCS_HHCCtrlSt	Bigint  comment ' 默认值-99999 HHC(Hill Hold Control) control status',
    BCS_HHCErrSt	Bigint  comment ' 默认值-99999 HHC(Hill Hold Control) error status',
    BCS_MasterCylinderPr	DECIMAL(18, 8)  comment ' 默认值-99999 Master cylinder pressure',
    BCS_MasterCylinderPres	Bigint  comment ' 默认值-99999 Current pressure of the master cylinder pressure sensor in the ESP. Raw value without offsetcompensation.',
    BCS_MasterCylinderPrOffset	DECIMAL(18, 8)  comment ' 默认值-99999 Master cylinder pressure offset',
    BCS_MasterCylinderPrOffsetVD	Bigint  comment ' 默认值-99999 Master cylinder pressure offset valid value',
    BCS_MasterCylinderPrVD	Bigint  comment ' 默认值-99999 The valid value of BCS_MasterCylinderPr',
    BCS_MaxEstimatedWheelPres	Bigint  comment ' 默认值-99999 Maximum of the estimated wheel pressures.',
    BCS_NoBrakeForce	Bigint  comment ' 默认值-99999 No brake pressure applied,generally it regards wheelcylinder presure',
    BCS_ParkingReqToEPB	Bigint  comment ' 默认值-99999 Indicates the release/lock brake request to EPB',
    BCS_PedalForceCompenasationSt	Bigint  comment ' 默认值-99999 Control state of force-blending interface to activate or hold pedal force compenasation(PFC)',
    BCS_QDCACC	Bigint  comment ' 默认值-99999 ACC error detected by ESP, like timeout or alivecounter error.The error should distinguish reversible and irreversible errors.',
    BCS_RegenModulationAvailable	Bigint  comment ' 默认值-99999 Indicate whether ESP can follow ePedal request andmodify the recuperation torque',
    BCS_RegenModuleActive	Bigint  comment ' 默认值-99999 Reduce repcuperation torque requested by oppotizeTCS control active status',
    BCS_RLWheelRotatedDirection	Bigint  comment ' 默认值-99999 RL wheel rotate direction',
    BCS_RLWheelRotatedDirectionAPA	Bigint  comment ' 默认值-99999 RL wheel rotate direction for APA',
    BCS_RLWheelRotatedDirectionVD	Bigint  comment ' 默认值-99999 RL wheel rotate direction validity',
    BCS_RLWheelSpd	DECIMAL(18, 8)  comment ' 默认值-99999 Current wheel speed information of rear left wheel',
    BCS_RLWheelSpdVD	Bigint  comment ' 默认值-99999 Quality/fault information to current wheel speed of front left wheel,be used for validity of BCS_RLWheelSpd and BCS_RLWheelSpdEdgesSum signal',
    BCS_RRWheelRotatedDirection	Bigint  comment ' 默认值-99999 RR wheel rotate direction',
    BCS_RRWheelRotatedDirectionAPA	Bigint  comment ' 默认值-99999 RR wheel rotate direction for APA',
    BCS_RRWheelRotatedDirectionVD	Bigint  comment ' 默认值-99999 RR wheel rotate direction validity',
    BCS_RRWheelSpd	DECIMAL(18, 8)  comment ' 默认值-99999 Current wheel speed information of rear right wheel',
    BCS_RRWheelSpdVD	Bigint  comment ' 默认值-99999 Quality/fault information to current wheel speed of RRont left wheel,be used for validity of BCS_RRWheelSpd and BCS_RRWheelSpdEdgesSum signal',
    BCS_TargetRecpTorqRqFA	Bigint  comment ' 默认值-99999 Target recuperation torque request by BCS to generator,applies to 4WD and front wheel drive',
    BCS_TargetRecpTorqRqFASt	Bigint  comment ' 默认值-99999 Status of target recuperation torque request by BCS to generator,applies to 4WD and front wheel drive',
    BCS_TCSActiveSt	Bigint  comment ' 默认值-99999 Indication that TCS system currently performs abrake/engine intervention',
    BCS_TCSFaultSt	Bigint  comment ' 默认值-99999 TCS is switched off due to detected failure',
    BCS_TCSOff	Bigint  comment ' 默认值-99999 TCS is switched off',
    BCS_VDCActiveSt	Bigint  comment ' 默认值-99999 Indication that VDC system currently performs a brake/engine intervention when ESP adjust theposture of vehicle',
    BCS_VDCFaultSt	Bigint  comment ' 默认值-99999 VDC is switched off due to detected failure',
    BCS_VDCOff	Bigint  comment ' 默认值-99999 VDC is switched off',
    BCS_VehicleStandStillSt	Bigint  comment ' 默认值-99999 Indicating whether the vehicle is standstill or not; must not be set until standstill is surely reached.',
    BCS_VehLaltrlAccelOffset	DECIMAL(18, 8)  comment ' 默认值-99999 Actual vehicle lateral acceleration offset',
    BCS_VehLongAccelOffset	DECIMAL(18, 8)  comment ' 默认值-99999 Actual vehicle longitudinal acceleration offset',
    BCS_VehSpd	DECIMAL(18, 8)  comment ' 默认值-99999 Vehicle speed',
    BCS_VehSpdVD	Bigint  comment ' 默认值-99999 Quality/fault information to vehicle speed',
    BCS_VrtMasterCylinderPresSt	Bigint  comment ' 默认值-99999 Status of BCS_VrtMasterCylinderPres',
    BCS_YawRate	DECIMAL(18, 8)  comment ' 默认值-99999 Yaw rate',
    BCS_YawRateOffset	DECIMAL(18, 8)  comment ' 默认值-99999 Yaw rate offset',
    BCS_YawRateSt	Bigint  comment ' 默认值-99999 Yaw rate status',
    BMS_12Volt	DECIMAL(18, 8)  comment ' 默认值-99999 Voltage of 12V-battery',
    BMS_AcChgCurrMax	DECIMAL(18, 8)  comment ' 默认值-99999 Maximum permissive AC charge current of HV battery',
    BMS_AcChgVoltMax	DECIMAL(18, 8)  comment ' 默认值-99999 Maximum permissive AC charge valtage of HV battery',
    BMS_BalExecutionStatus	Bigint  comment ' 默认值-99999 Balancing execution status',
    BMS_BattChgErr	Bigint  comment ' 默认值-99999 battery AC charge error',
    BMS_BattChgSt	Bigint  comment ' 默认值-99999 battery AC charge state',
    BMS_BattCurr	DECIMAL(18, 8)  comment ' 默认值-99999 actual current of battery',
    BMS_BattSocAct	DECIMAL(18, 8)  comment ' 默认值-99999 Average SOC of battery pack',
    BMS_BattSocDisp	DECIMAL(18, 8)  comment ' 默认值-99999 Average SOC of battery pack for display',
    BMS_BattSoe	DECIMAL(18, 8)  comment ' 默认值-99999 Average SOE of battery pack',
    BMS_BattSoh	DECIMAL(18, 8)  comment ' 默认值-99999 SOH of battery pack',
    BMS_BattTempAvg	DECIMAL(18, 8)  comment ' 默认值-99999 Average battery temperature',
    BMS_BattTempMax	DECIMAL(18, 8)  comment ' 默认值-99999 Max temperature of battery pack',
    BMS_BattTempMin	DECIMAL(18, 8)  comment ' 默认值-99999 Min temperature of battery pack',
    BMS_BattTypeStBD	Bigint  comment ' 默认值-99999 Battery type status for configuration',
    BMS_BattVolt	Bigint  comment ' 默认值-99999 actual voltage of battery pack (inside of main relay)',
    BMS_BusVoltBD	Bigint  comment ' 默认值-99999 Voltage outside positive contactor',
    BMS_CellVoltAvg	DECIMAL(18, 8)  comment ' 默认值-99999 Average value of cell voltage',
    BMS_CellVoltMax	DECIMAL(18, 8)  comment ' 默认值-99999 Maximum value of cell voltage',
    BMS_CellVoltMin	DECIMAL(18, 8)  comment ' 默认值-99999 Minimum value of cell voltage',
    BMS_CellVoltSumBD	Bigint  comment ' 默认值-99999 sum of a pack all cell voltage',
    BMS_ChgComplRemHour	Bigint  comment ' 默认值-99999 Charge completed time for hour part for display',
    BMS_ChgComplRemMinute	Bigint  comment ' 默认值-99999 Charge completed time for minute part for display',
    BMS_ChgCurrMax_Contns	DECIMAL(18, 8)  comment ' 默认值-99999 Max charge current limit for continues time',
    BMS_ChgCurrMax_Peak	DECIMAL(18, 8)  comment ' 默认值-99999 Max charge current limit for peak time',
    BMS_ChgVoltMax_Contns	Bigint  comment ' 默认值-99999 Max charge voltage limit for continues time',
    BMS_ChgVoltMax_Peak	Bigint  comment ' 默认值-99999 Max charge voltage limit for peak time',
    BMS_CoolantFlowReq	Bigint  comment ' 默认值-99999 Target flow speed of coolant from BMS',
    BMS_CoolantTargTemp	Bigint  comment ' 默认值-99999 Target temperature of coolant from BMS',
    BMS_DcChargerSt	Bigint  comment ' 默认值-99999 DC charger connet link state',
    BMS_DcChgConfigSt	Bigint  comment ' 默认值-99999 BMS configure with quick charger state',
    BMS_DcChgCurrMax	DECIMAL(18, 8)  comment ' 默认值-99999 Maximum permissive DC charge current of HV battery',
    BMS_DcChgErrLvl	Bigint  comment ' 默认值-99999 battery charge error state',
    BMS_DcChgInfoSt	Bigint  comment ' 默认值-99999 BMS information on DC charging state. Detailed information for BMS_DcChgConfigSt',
    BMS_DcChgrCurrCap	Bigint  comment ' 默认值-99999 Max available charging current of DC charger',
    BMS_DcChgrErrInfo	Bigint  comment ' 默认值-99999 DC charger error information',
    BMS_DcChgrVoltCap	Bigint  comment ' 默认值-99999 Max available charging voltage of DC charger',
    BMS_DcChgSt	Bigint  comment ' 默认值-99999 battery charge state for DC charging',
    BMS_DcChgVoltMax	DECIMAL(18, 8)  comment ' 默认值-99999 Maximum permissive DC charge valtage of HV battery',
    BMS_DchgCurrMax_Contns	DECIMAL(18, 8)  comment ' 默认值-99999 Max discharge current limit continues time',
    BMS_DchgCurrMax_Peak	DECIMAL(18, 8)  comment ' 默认值-99999 Max discharge current limit peak time',
    BMS_DchgVoltMax_Contns	Bigint  comment ' 默认值-99999 Max discharge voltage limit continues time',
    BMS_DchgVoltMax_Peak	Bigint  comment ' 默认值-99999 Max discharge voltage limit peak time',
    BMS_DCVoltBD	Bigint  comment ' 默认值-99999 Voltage outside DC charging contactor',
    BMS_DiagErrCode	Bigint  comment ' 默认值-99999 BMS diagnostics error code',
    BMS_EmgLineSt	Bigint  comment ' 默认值-99999 the status of emergency line detected by BMS',
    BMS_ErrID10BD	Bigint  comment ' 默认值-99999 BMS_ErrID10',
    BMS_ErrID1BD	Bigint  comment ' 默认值-99999 BMS_ErrID1',
    BMS_ErrID2BD	Bigint  comment ' 默认值-99999 BMS_ErrID2',
    BMS_ErrID3BD	Bigint  comment ' 默认值-99999 BMS_ErrID3',
    BMS_ErrID4BD	Bigint  comment ' 默认值-99999 BMS_ErrID4',
    BMS_ErrID5BD	Bigint  comment ' 默认值-99999 BMS_ErrID5',
    BMS_ErrID6BD	Bigint  comment ' 默认值-99999 BMS_ErrID6',
    BMS_ErrID7BD	Bigint  comment ' 默认值-99999 BMS_ErrID7',
    BMS_ErrID8BD	Bigint  comment ' 默认值-99999 BMS_ErrID8',
    BMS_ErrID9BD	Bigint  comment ' 默认值-99999 BMS_ErrID9',
    BMS_FaultLampInd	Bigint  comment ' 默认值-99999 Warning indicator to lighten fault lamp (MalfunctionIndication Lamp, MIL)',
    BMS_HvBattCoolErrSt	Bigint  comment ' 默认值-99999 Battery cooling fault status',
    BMS_HVBattElec	DECIMAL(18, 8)  comment ' 默认值-99999 Max electricity of Battery',
    BMS_HVBattSt	Bigint  comment ' 默认值-99999 working state of HV battery system',
    BMS_HvilSt	Bigint  comment ' 默认值-99999 HVIL status monitored by BMS',
    BMS_InslRes	Bigint  comment ' 默认值-99999 isolation resistence value, its range is from 0 to 1M ohm',
    BMS_InslSt	Bigint  comment ' 默认值-99999 Battery insulation status',
    BMS_LastTimeChgEnergy	DECIMAL(18, 8)  comment ' 默认值-99999 Last time charging energy of battery, which comes from AC charging or DC charging.',
    BMS_NegVoltBD	Bigint  comment ' 默认值-99999 Voltage outside negative contactor',
    BMS_PrecResOverTemp	Bigint  comment ' 默认值-99999 Flag signal for precharge resistor over temperature',
    BMS_PwrDwnReq	Bigint  comment ' 默认值-99999 Emergency power-off warning. when the HV battery needs an emergency power-off, this signal is used to notify each HV node. The received node should reduce their power  to 0  as soon as possible.',
    BMS_SVBD	Bigint  comment ' 默认值-99999 BMS ecan software version',
    BMS_ThermalReq	Bigint  comment ' 默认值-99999 BMS thermal request to VCU',
    BMS_ThermalRunawayErr	Bigint  comment ' 默认值-99999 thermal runaway error alarm',
    BMS_ThermalRunawayTS10BD	Bigint  comment ' 默认值-99999 Thermal Runaway Trigger Condition10',
    BMS_ThermalRunawayTS11BD	Bigint  comment ' 默认值-99999 Thermal Runaway Trigger Condition11',
    BMS_ThermalRunawayTS1BD	Bigint  comment ' 默认值-99999 Thermal Runaway Trigger Condition1',
    BMS_ThermalRunawayTS2BD	Bigint  comment ' 默认值-99999 Thermal Runaway Trigger Condition2',
    BMS_ThermalRunawayTS3BD	Bigint  comment ' 默认值-99999 Thermal Runaway Trigger Condition3',
    BMS_ThermalRunawayTS4BD	Bigint  comment ' 默认值-99999 Thermal Runaway Trigger Condition4',
    BMS_ThermalRunawayTS5BD	Bigint  comment ' 默认值-99999 Thermal Runaway Trigger Condition5',
    BMS_ThermalRunawayTS6BD	Bigint  comment ' 默认值-99999 Thermal Runaway Trigger Condition6',
    BMS_ThermalRunawayTS7BD	Bigint  comment ' 默认值-99999 Thermal Runaway Trigger Condition7',
    BMS_ThermalRunawayTS8BD	Bigint  comment ' 默认值-99999 Thermal Runaway Trigger Condition8',
    BMS_ThermalRunawayTS9BD	Bigint  comment ' 默认值-99999 Thermal Runaway Trigger Condition9',
    BMS_TotalChgEnergy	Bigint  comment ' 默认值-99999 Totoal charging energy of battery, including AC charging, DC charging and energy regeneration.',
    DCU_DiagErrCode	Bigint  comment ' 默认值-99999 DCU diagnostics error code',
    DCU_FaultLampInd	Bigint  comment ' 默认值-99999 Warning indicator to lighten fault lamp (MalfunctionIndication Lamp,MIL)',
    DCU_HvilSt	Bigint  comment ' 默认值-99999 DCU send HVIL status by itself',
    DCU_IdcAct	Bigint  comment ' 默认值-99999 actual current at HV of DCU',
    DCU_InvtTemp	Bigint  comment ' 默认值-99999 Current temperature of inverter',
    DCU_ModeSt	Bigint  comment ' 默认值-99999 mode status of drive motor',
    DCU_RotSpdAct	Bigint  comment ' 默认值-99999 actual rotation speed of drvie motor',
    DCU_RotTemp	Bigint  comment ' 默认值-99999 Current temperature of rotor',
    DCU_StatTemp	Bigint  comment ' 默认值-99999 Current temperature of stator',
    DCU_TempCoolant	Bigint  comment ' 默认值-99999 temperature of inverter cooling water',
    DCU_TorqAct	Bigint  comment ' 默认值-99999 actual torque of drive motor',
    DCU_UdcAct	Bigint  comment ' 默认值-99999 actual voltage at HV of DCU',
    EBB_ActOutputRodTravel	Bigint  comment ' 默认值-99999 Current value for output rod in EBB indicates the shifted volume in master cylinder. Gives information, if the compensation port is closed. Includes e.g. the pedal force compensation control for Hev.',
    EBB_ActOutputRodTravelSt	Bigint  comment ' 默认值-99999 Status of EBB_ActOutputRodTravel',
    EBB_BCSReqBrkPedalApplied	Bigint  comment ' 默认值-99999 information about the driver attendance for RPA，if the Brake pedal is applied by the driver',
    EBB_BCSReqBrkPedalAppliedSt	Bigint  comment ' 默认值-99999 Status of EBB_BCSBrkPedalApplied for RPA',
    EBB_BrkFxCpb	Bigint  comment ' 默认值-99999 Brake system capacity for ADAS',
    EBB_BrkPedalModeCfgSt	Bigint  comment ' 默认值-99999 Brake Pedal feeling Mode configuration status',
    EBB_CompatibilityIndex	Bigint  comment ' 默认值-99999 index to ensure the compatibility between iB and ESP software',
    EBB_ExterBrkReqDominate	Bigint  comment ' 默认值-99999 Flag to signal if driver request or external brakerequest is dominating.',
    EBB_HBCReq	Bigint  comment ' 默认值-99999 With this signal EBB requests the fail boost functionof ESP，Hydraulic Booster Failure Compensation(HBC).',
    EBB_OutputRodTravelDriverReq	Bigint  comment ' 默认值-99999 Information of driver brake request. Calculation of:- target value  for output rod in EBB Also shows pedaltravel with active pressure increase via EBB',
    EBB_OutputRodTravelDriverReqSt	Bigint  comment ' 默认值-99999 Status of EBB_OutputRodTravelDriverReq',
    EBB_WarnLamp	Bigint  comment ' 默认值-99999 EBB warning Lamp',
    EBS_BattCurrent	Bigint  comment ' 默认值-99999 Battery current',
    EBS_BattQuiescentCurrent	DECIMAL(18, 8)  comment ' 默认值-99999 Battery quiescent current',
    EBS_BattTemp	Bigint  comment ' 默认值-99999 Battery temperature',
    EBS_BattVolt	DECIMAL(18, 8)  comment ' 默认值-99999 Battery voltage',
    EBS_CurrentRange	Bigint  comment ' 默认值-99999 Battery current range',
    EBS_CurrentSt	Bigint  comment ' 默认值-99999 current status',
    EBS_Q_Charge	DECIMAL(18, 8)  comment ' 默认值-99999 accumulated battery charge',
    EBS_Q_Discharge	DECIMAL(18, 8)  comment ' 默认值-99999 accumulated battery discharge',
    EBS_SOC	Bigint  comment ' 默认值-99999 State of Charge',
    EBS_SOC_STATE	Bigint  comment ' 默认值-99999 SOC Status',
    EBS_SOFV_Restart	DECIMAL(18, 8)  comment ' 默认值-99999 Battery voltage at cranking peak without per- discharge',
    EBS_SOFV_Restart_St	Bigint  comment ' 默认值-99999 SOFV_Restart Status',
    EBS_SOFV_StopEnable	DECIMAL(18, 8)  comment ' 默认值-99999 Battery voltage at cranking peak with per-discharge',
    EBS_SOFV_StopEnable_St	Bigint  comment ' 默认值-99999 SOFV_StopEnable Status',
    EBS_SOH_COR	DECIMAL(18, 8)  comment ' 默认值-99999 State of health(corrosion)',
    EBS_SOH_COR_St	Bigint  comment ' 默认值-99999 SOH_COR Status',
    EBS_SOH_LAM	DECIMAL(18, 8)  comment ' 默认值-99999 State of health(Loss of active mass)',
    EBS_SOH_LAM_St	Bigint  comment ' 默认值-99999 SOH_LAM Status',
    EBS_SOH_SUL	Bigint  comment ' 默认值-99999 Max.possible SOC,reduced by sulphation',
    EBS_SOH_SUL_St	Bigint  comment ' 默认值-99999 SOH_SUL Status',
    EBS_TempSt	Bigint  comment ' 默认值-99999 Temperature Status',
    EBS_VoltSt	Bigint  comment ' 默认值-99999 voltage Status',
    EMS_GasPedalActPstforMRR	DECIMAL(18, 8)  comment ' 默认值-99999 Current accelerate pedal actual position（when drivers press on the brake）',
    EMS_GasPedalActPstforMRRVD	Bigint  comment ' 默认值-99999 EMS_GasPedalActPstforMRR Valid Data',
    EPB_AchievedClampForce	Bigint  comment ' 默认值-99999 EPB clamp force',
    EPB_ActuatorSt_L	Bigint  comment ' 默认值-99999 EPB left actuator status',
    EPB_ActuatorSt_R	Bigint  comment ' 默认值-99999 EPB right  actuator status',
    EPB_DynamicApplySt	Bigint  comment ' 默认值-99999 EPB dynamic apply status',
    EPB_FailSt	Bigint  comment ' 默认值-99999 EPB fail status,to indicate wether EPB can responseto external apply  request or not',
    EPB_MotorCurrent_L	DECIMAL(18, 8)  comment ' 默认值-99999 EPB left motor current',
    EPB_MotorCurrent_R	DECIMAL(18, 8)  comment ' 默认值-99999 EPB rignt motor current',
    EPB_SwitchSt	Bigint  comment ' 默认值-99999 EPB switch status',
    EPB_SwitchStVD	Bigint  comment ' 默认值-99999 EPB switch status validity',
    EPB_SysSt	Bigint  comment ' 默认值-99999 EPB system status',
    EPS_ElecPowerConsumption	DECIMAL(18, 8)  comment ' 默认值-99999 EPS consumption current',
    EPS_ElecPowerConsumptionVD	Bigint  comment ' 默认值-99999 EPS Motor Current Consumption validvalue',
    EPS_FunctionStyleSt	Bigint  comment ' 默认值-99999 EPS function style state',
    EPS_HandsOffDetSt	Bigint  comment ' 默认值-99999 Hands Off Detected States',
    EPS_HandsOffDetStVD	Bigint  comment ' 默认值-99999 Hands Off Detected States valid value',
    EPS_LKACtrlAbortFeedback	Bigint  comment ' 默认值-99999 Feedback to LKS abort reason',
    EPS_LKACtrlDlvdValue	DECIMAL(18, 8)  comment ' 默认值-99999 LKA Control Delivered Value',
    EPS_LKACtrlDlvdValueVD	Bigint  comment ' 默认值-99999 LKA Control Delivered Value valid value',
    EPS_LKACtrlSt	Bigint  comment ' 默认值-99999 EPS cotrol status by LKS',
    EPS_PAS_AbortFeedback	Bigint  comment ' 默认值-99999 Feedback to PAS abort reason',
    EPS_PAS_EpasFailed	Bigint  comment ' 默认值-99999 Feedback to PAS failure status',
    EPS_PAS_ReqFeedback	Bigint  comment ' 默认值-99999 Feedback to PASs control request',
    EPS_SteeringAngle	DECIMAL(18, 8)  comment ' 默认值-99999 Steering wheel angle',
    EPS_SteeringAngleSpd	Bigint  comment ' 默认值-99999 steering wheel angle speed',
    EPS_SteeringAngleSpdVD	Bigint  comment ' 默认值-99999 Steering wheel angle speed valid value',
    EPS_SteeringAngleVD	Bigint  comment ' 默认值-99999 Steering wheel angle valid value',
    EPS_SteeringModeSt	Bigint  comment ' 默认值-99999 EPS steering mode status',
    EPS_StrngWhlTorq	DECIMAL(18, 8)  comment ' 默认值-99999 Steering Wheel Torque',
    EPS_StrngWhlTorqVD	Bigint  comment ' 默认值-99999 Steering Wheel Torque Valid Value',
    EPS_WarnLamp	Bigint  comment ' 默认值-99999 Steering Warning Lamp',
    FAPA_APAActFuncInd	Bigint  comment ' 默认值-99999 Auto_parking Active Function Indication',
    FAPA_APAAuthst	Bigint  comment ' 默认值-99999 APA Authst with SBM',
    FAPA_LSMSubMTLevel	Bigint  comment ' 默认值-99999 Needs to be set to MTLevel_12 to activate. Level_23 not functional for BL0',
    FAPA_LSMSubMTLong	Bigint  comment ' 默认值-99999 Comfort = Standard control, Emergency = Instant emergency braking',
    FAPA_LSMSubMTReq	Bigint  comment ' 默认值-99999 Needs to be set to LSM to activate. "MTReq_Drive" is not used, can be ignored.',
    FAPA_LSMVehDirRq	Bigint  comment ' 默认值-99999 Direction request',
    FAPA_LSMVehSecReq	Bigint  comment ' 默认值-99999 Secure Request',
    FAPA_PASRemoteParkingEnable	Bigint  comment ' 默认值-99999 FAPA PAS Remote Parking Enable',
    FAPA_PASRemoteParkingMode	Bigint  comment ' 默认值-99999 PAS Remote parking Mode',
    FLDCM_FLWinSt	Bigint  comment ' 默认值-99999 Front left window status',
    FLDCM_RLWinSt	Bigint  comment ' 默认值-99999 Rear left window status',
    FRDCM_FRWinSt	Bigint  comment ' 默认值-99999 Front right window status',
    FRDCM_RRWinSt	Bigint  comment ' 默认值-99999 Rear right window status',
    GSM_DriveMode	Bigint  comment ' 默认值-99999 Drive mode',
    GSM_GearShiftLeverPstReq	Bigint  comment ' 默认值-99999 Gear shift lever postion request',
    HVAC_ACSt	Bigint  comment ' 默认值-99999 The HVAC A/C state display',
    HVAC_AirCirculationSt	Bigint  comment ' 默认值-99999 Airconditionor air circulation state',
    HVAC_AirCompressorReq	Bigint  comment ' 默认值-99999 Air compressor request',
    HVAC_AutoSt	Bigint  comment ' 默认值-99999 The HVAC auto state display',
    HVAC_CompressorSpdReq	Bigint  comment ' 默认值-99999 AC Compressor speed require',
    HVAC_CoolFanDutyCycleReq	DECIMAL(18, 8)  comment ' 默认值-99999 Cool fan duty cycle request to VCU',
    HVAC_CoolFanDutyCycleReqVD	Bigint  comment ' 默认值-99999 Indication HVAC_CoolFanDutyCycleReq validity',
    HVAC_CorrectedExterTemp	DECIMAL(18, 8)  comment ' 默认值-99999 External temperature',
    HVAC_DisinfectenSt	Bigint  comment ' 默认值-99999 HVAC disinfecten status',
    HVAC_DriverTempSelect	DECIMAL(18, 8)  comment ' 默认值-99999 The selected temperature of Driver side',
    HVAC_ECPFault	Bigint  comment ' 默认值-99999 ECP now can be used:valid or not',
    HVAC_ECPPwrConsump	Bigint  comment ' 默认值-99999 ECP power consumption',
    HVAC_PsnTempSelect	DECIMAL(18, 8)  comment ' 默认值-99999 The selected temperature of passenger side',
    HVAC_PTCCoolantTemp	Bigint  comment ' 默认值-99999 PTCs media temperture, internal signal in PTC',
    HVAC_PTCFault	Bigint  comment ' 默认值-99999 PTC now can be used:valid or not',
    HVAC_PTCPwrConsmp	Bigint  comment ' 默认值-99999 PTC power consumption',
    HVAC_RawCabinTemp	DECIMAL(18, 8)  comment ' 默认值-99999 Raw cabin temperature',
    HVAC_RawCabinTempVD	Bigint  comment ' 默认值-99999 Signal HVAC_RawCabinTemp validity',
    HVAC_RawEvaTemp	DECIMAL(18, 8)  comment ' 默认值-99999 Raw evaporator temperature',
    HVAC_RawExterTemp	DECIMAL(18, 8)  comment ' 默认值-99999 Raw External temperature',
    HVAC_RawExterTempVD	Bigint  comment ' 默认值-99999 Raw External temperature valid data',
    HVAC_StsCabinCoolPrioReq	Bigint  comment ' 默认值-99999 Cabin cool down climatization prioritization request',
    HVAC_StsCabinHeatPrioReq	Bigint  comment ' 默认值-99999 Cabin heat up climatization prioritization request',
    HVAC_TelematicsSt	Bigint  comment ' 默认值-99999 HVAC Telematics Status',
    HVAC_TempSelect	DECIMAL(18, 8)  comment ' 默认值-99999 The temperature selected on auto HVAC',
    HVAC_WindExitMode	Bigint  comment ' 默认值-99999 The wind exit mode',
    HVAC_WindExitSpd	Bigint  comment ' 默认值-99999 The wind exit speed',
    HVSM_FLHeatingActLevel	Bigint  comment ' 默认值-99999 Front left seat heating actual level',
    HVSM_FLHVSMAutoModeSt	Bigint  comment ' 默认值-99999 Front left seat heating/ventilating auto mode status',
    HVSM_FLSeatTemp	DECIMAL(18, 8)  comment ' 默认值-99999 Front left seat temperature',
    HVSM_FLSeatTempVD	Bigint  comment ' 默认值-99999 Front left seat ventilating actual level validity',
    HVSM_FLVentilatingActLevel	Bigint  comment ' 默认值-99999 Front left seat ventilating actual level',
    HVSM_FRHeatingActLevel	Bigint  comment ' 默认值-99999 Front right seat heating actual level',
    HVSM_FRHVSMAutoModeSt	Bigint  comment ' 默认值-99999 Front right seat heating/ventilating auto mode status',
    HVSM_FRSeatTemp	Bigint  comment ' 默认值-99999 Front right seat temperature',
    HVSM_FRSeatTempVD	Bigint  comment ' 默认值-99999 Front right seat ventilating actual level validity',
    HVSM_FRVentilatingActLevel	Bigint  comment ' 默认值-99999 Front right seat ventilating actual level',
    ICM_AvaibleDriveDistance	Bigint  comment ' 默认值-99999 The available driving distance according to the fuel',
    ICM_BackLightLevel	Bigint  comment ' 默认值-99999 Back light level',
    ICM_BattVolt	DECIMAL(18, 8)  comment ' 默认值-99999 Battery voltage',
    ICM_BFLWarning	Bigint  comment ' 默认值-99999 Brake fluid level low warning',
    ICM_DisFail	Bigint  comment ' 默认值-99999 Error in the display',
    ICM_SpdWarnCfgSt	Bigint  comment ' 默认值-99999 Speed warning configuration status',
    ICM_TotalOdometer	Bigint  comment ' 默认值-99999 Total odometer',
    ICM_TotalOdometer_accurate	DECIMAL(18, 8)  comment ' 默认值-99999 ODO value as accuracy of 0.1 km',
    ICM_VehAverageSpd	Bigint  comment ' 默认值-99999 Vehicle average speed',
    ICM_VehicleBrakeSt	Bigint  comment ' 默认值-99999 Indicate the vehicle brake status,ICM judge from theHand brake status or the EPB brake status',
    ICM_VehInsSpd	Bigint  comment ' 默认值-99999 Vehicle instantaneous speed',
    ICM_VehRunningTime	Bigint  comment ' 默认值-99999 Vehicle running time',
    ICM_WFLWarning	Bigint  comment ' 默认值-99999 Washer fluid level low warning',
    IFC_CameraBlockageSt	Bigint  comment ' 默认值-99999 IFC(Intelligent Front Camera) camera blockagestatus',
    IFC_ELKSt	Bigint  comment ' 默认值-99999 ELK feature status',
    IFC_ELKWarnL	Bigint  comment ' 默认值-99999 ELKA warning left',
    IFC_ELKWarnR	Bigint  comment ' 默认值-99999 ELKA warning right',
    IFC_HMA_St	Bigint  comment ' 默认值-99999 HMA (High Beam Assistant)status',
    IFC_HWAHF_HandsOnIcon	Bigint  comment ' 默认值-99999 TJA/ICA and HWA HandsOff function request driver hands on icon',
    IFC_LateralCtrlQuitWarn	Bigint  comment ' 默认值-99999 Lateral control quit warning, which would be used to let the driver pay attention to the situation that lateral control is quit while the longitudinal contrl may still working.',
    IFC_LeftTrackingSt	Bigint  comment ' 默认值-99999 Left line tracking/intervention/warning status',
    IFC_LKS_LaneAssistType	Bigint  comment ' 默认值-99999 operation mode of IFC(Intelligent Front Camera)',
    IFC_LKS_St	Bigint  comment ' 默认值-99999 LKS state information',
    IFC_LKS_TakeoverReq	Bigint  comment ' 默认值-99999 Take over request to driver',
    IFC_RightTrackingSt	Bigint  comment ' 默认值-99999 Right line tracking/intervention/warning status',
    IFC_SysCalibrationSt	Bigint  comment ' 默认值-99999 IFC(Intelligent Front Camera) system calibration status',
    IFC_TJA_ICA_St	Bigint  comment ' 默认值-99999 TJA/ICA（Traffic Jam Assist/Integrated Cruise Assist） Status',
    IFC_TorqueReq	DECIMAL(18, 8)  comment ' 默认值-99999 Output LKS torque request',
    IFC_TorqueReqSt	Bigint  comment ' 默认值-99999 Inidicating LDS torque cotrol request',
    IFC_TSR_AudioWarnEnable	Bigint  comment ' 默认值-99999 TSR(Traffic Sign Recognition) audio warning on offstatus',
    IFC_TSR_OperatingSt	Bigint  comment ' 默认值-99999 Operation status of traffic sign functions',
    IPS_ACHvilSt	Bigint  comment ' 默认值-99999 IPS send AC side HVIL status measued by itself',
    IPS_DCDC_KL15	Bigint  comment ' 默认值-99999 IPS or DCDC Enable state',
    IPS_DCDC_KL30Volt	DECIMAL(18, 8)  comment ' 默认值-99999 IPS or DCDC LV power supply voltage',
    IPS_DCDCCurrHvAct	DECIMAL(18, 8)  comment ' 默认值-99999 actual (input) current at HV voltage of DCDC',
    IPS_DCDCCurrLvAct	Bigint  comment ' 默认值-99999 actual (output) Current at LV voltage of DCDC',
    IPS_DCDCDiagErrCode	Bigint  comment ' 默认值-99999 DCDC diagnostics error code',
    IPS_DCDCFaultLampInd	Bigint  comment ' 默认值-99999 Warning indicator to lighten fault lamp (Malfunction Indication Lamp,MIL',
    IPS_DCDCFlowReq	Bigint  comment ' 默认值-99999 The DCDC required coolant flow speed  (L/min)',
    IPS_DCDCModeSt	Bigint  comment ' 默认值-99999 mode status of DCDC',
    IPS_DCDCState1	Bigint  comment ' 默认值-99999 DCDC state information 1',
    IPS_DCDCState2	Bigint  comment ' 默认值-99999 DCDC state information 2',
    IPS_DCDCState3	Bigint  comment ' 默认值-99999 DCDC state information 3',
    IPS_DCDCState4	Bigint  comment ' 默认值-99999 DCDC state information 4',
    IPS_DCDCState5	Bigint  comment ' 默认值-99999 DCDC state information 5',
    IPS_DCDCTempAct	Bigint  comment ' 默认值-99999 Actual temperature of DCDC',
    IPS_DCDCVoltHvAct	Bigint  comment ' 默认值-99999 actual HV voltage at DCDC',
    IPS_DCDCVoltLvAct	DECIMAL(18, 8)  comment ' 默认值-99999 actual LV voltage at DCDC',
    IPS_HVDCHVilSt	Bigint  comment ' 默认值-99999 IPS send DC side HVIL status measued by itself',
    IPS_OBCCC_Cap	Bigint  comment ' 默认值-99999 AC charging capability of the charging cable detected by OBC',
    IPS_OBCCC_Res	Bigint  comment ' 默认值-99999 CC Resistance value in Ohm',
    IPS_OBCCC_St	Bigint  comment ' 默认值-99999 Status of slow charging cable connection (CC) including type of connected cable (charging/V2V, or V2L)',
    IPS_OBCCp_DutyCycle	DECIMAL(18, 8)  comment ' 默认值-99999 CP Duty',
    IPS_OBCCpFreqSt	Bigint  comment ' 默认值-99999 CP frequency is in the GB range',
    IPS_OBCCpS2St	Bigint  comment ' 默认值-99999 S2 swtich state',
    IPS_OBCCPSt	Bigint  comment ' 默认值-99999 Status of control pilot signal (CP) for charging',
    IPS_OBCCPVolt	DECIMAL(18, 8)  comment ' 默认值-99999 CP high level',
    IPS_OBCCurrActL1	DECIMAL(18, 8)  comment ' 默认值-99999 L1 phase current',
    IPS_OBCDiagErrCode	Bigint  comment ' 默认值-99999 OBC diagnostics error code',
    IPS_OBCFaultLampInd	Bigint  comment ' 默认值-99999 Warning indicator to lighten fault lamp (Malfunction Indication Lamp,MIL',
    IPS_OBCFlowReq	Bigint  comment ' 默认值-99999 The OBC required coolant flow speed  (L/min)',
    IPS_OBCHvDcCurrAct	DECIMAL(18, 8)  comment ' 默认值-99999 OBC HVDC actual current (Positive current+： Charging mode output current from IPS to HVBAT, Negative current-：DisCharging mode input currentfrom HVBAT)',
    IPS_OBCHvDcVoltAct	Bigint  comment ' 默认值-99999 OBC HVDC voltage',
    IPS_OBCModeSt	Bigint  comment ' 默认值-99999 OBC mode state',
    IPS_OBCState1	Bigint  comment ' 默认值-99999 OBC state information 1',
    IPS_OBCState2	Bigint  comment ' 默认值-99999 OBC state information 2',
    IPS_OBCState3	Bigint  comment ' 默认值-99999 OBC state information 3',
    IPS_OBCState4	Bigint  comment ' 默认值-99999 OBC state information 4',
    IPS_OBCState5	Bigint  comment ' 默认值-99999 OBC state information 5',
    IPS_OBCTempAct	Bigint  comment ' 默认值-99999 OBC internal temperature',
    IPS_OBCUacActL1	Bigint  comment ' 默认值-99999 L1 phase voltage',
    MRR_ABALevel	Bigint  comment ' 默认值-99999 ABA(Adaptive Brake Assistance) level to the ESP HBA',
    MRR_ABAReq	Bigint  comment ' 默认值-99999 Request of the ABA support from ESP',
    MRR_ABPReq	Bigint  comment ' 默认值-99999 Request of the Prefill to ESP',
    MRR_ACCMode	Bigint  comment ' 默认值-99999 This signal indicates ACC(Adaptive cruise control)status',
    MRR_ACCRecpDecel	Bigint  comment ' 默认值-99999 Target deceleration value from ACC to VCU for for min braking or energy recuperation',
    MRR_ACCTakeOverReq	Bigint  comment ' 默认值-99999 ACC(Adaptive Cruise Control) request for driver takeover',
    MRR_ACCTextInfo	Bigint  comment ' 默认值-99999 ACC text infor for driver',
    MRR_ActTrqReq	Bigint  comment ' 默认值-99999 Effective target torque on wheel level',
    MRR_ActTrqReqVD	Bigint  comment ' 默认值-99999 Enable flag for EMS for realization of target torqueActTrqReq',
    MRR_AEB_PEDPFaultSt	Bigint  comment ' 默认值-99999 This signal indicates theAEB_PEDP(AEB_Pedestrian Protection) fault status',
    MRR_AEBDecelCtrlReq	Bigint  comment ' 默认值-99999 Request of the AEB deceleration control',
    MRR_AEBFaultSt	Bigint  comment ' 默认值-99999 This signal indicates the AEB(Auto EmerrgencyBraking) fault status',
    MRR_AEBInterventionSt	Bigint  comment ' 默认值-99999 This signal indicates if the AEB(Auto EmerrgencyBraking) intervents',
    MRR_AEBLVehHoldReq	Bigint  comment ' 默认值-99999 Request ESP to hold vehilce if AEB active andvehilce stopped',
    MRR_AEBOffSt	Bigint  comment ' 默认值-99999 This signal indicates if the AEB(Auto EmerrgencyBraking) is deactivated',
    MRR_AEBTargetDecel	DECIMAL(18, 8)  comment ' 默认值-99999 Target deceleration value from AEB(Automatic EmergencyBraking)/EBA(Emergence Braking Assist)',
    MRR_AWBLevel	Bigint  comment ' 默认值-99999 Different level request of the brake jerk',
    MRR_AWBReq	Bigint  comment ' 默认值-99999 Request of the brake jerk warning to ESP',
    MRR_FCWFaultSt	Bigint  comment ' 默认值-99999 This signal indicates the FCW (Front CollisionWarning) fault status',
    MRR_FCWLatentWarn	Bigint  comment ' 默认值-99999 Visual warning. used with signal MRR_ FCWActiveSt',
    MRR_FCWOffSt	Bigint  comment ' 默认值-99999 This signal indicates if the FCW (Front CollisionWarning) is deactivated',
    MRR_FCWPreWarn	Bigint  comment ' 默认值-99999 Acoustic pre warning.Used with  signal MRR_ FCWActiveSt',
    MRR_FCWWarmDistance	Bigint  comment ' 默认值-99999 FCW warming distance',
    MRR_ISLACC_St	Bigint  comment ' 默认值-99999 nan',
    MRR_LongCtrlAccelCtrlReq	Bigint  comment ' 默认值-99999 Request of the ACC Acceleration control',
    MRR_LongCtrlDecToStopReq	Bigint  comment ' 默认值-99999 The MRR plus request ESP/VLC to decelerate untillstandstill.',
    MRR_LongCtrlDriveOff	Bigint  comment ' 默认值-99999 MRRplus request ESP(CDD-S) drive off',
    MRR_LongCtrlModeForBrkSys	Bigint  comment ' 默认值-99999 ACC(Adaptive cruise control )Mode for ESP',
    MRR_LongCtrlShutdownReq	Bigint  comment ' 默认值-99999 The shutdown mode request to driving functionshutdown mode',
    MRR_LongCtrlTargetAccel	DECIMAL(18, 8)  comment ' 默认值-99999 ACC target acceleration for transmission',
    MRR_LongCtrlTargetAccelJerkMinValue	Bigint  comment ' 默认值-99999 The minimum allowed jerk of the target acceleration',
    MRR_LongCtrTargetAccelJerkMaxnValue	Bigint  comment ' 默认值-99999 The maximum allowed jerk of the target acceleration',
    MRR_ObjectCapturedSt	Bigint  comment ' 默认值-99999 Status of object capturing',
    MRR_PEBSObjType	Bigint  comment ' 默认值-99999 The type of SDF target object when PEBS(includled FCW/FCW-Peds or AEB/AEB-Peds )is active.',
    MRR_TauGapSet	Bigint  comment ' 默认值-99999 The set timeGap from driver, should be displayed to driver and if the set value changes',
    PAS_APA_ESPSpdLimit	Bigint  comment ' 默认值-99999 inform ESP the velocity maximum',
    PAS_APA_ESPStopDist	Bigint  comment ' 默认值-99999 Inform the ESP the parking target distance point',
    PAS_APAButtonPress	Bigint  comment ' 默认值-99999 APA button press status',
    PAS_APADrvReq	Bigint  comment ' 默认值-99999 APA Driver Operation Remind',
    PAS_APAModeInd	Bigint  comment ' 默认值-99999 APA mode indication',
    PAS_APAParkslotSt	Bigint  comment ' 默认值-99999 APA Parking Slot Direction',
    PAS_APAQuitInd	Bigint  comment ' 默认值-99999 APA Quit indication',
    PAS_APARecInd	Bigint  comment ' 默认值-99999 APA Recover indication',
    PAS_APASt	Bigint  comment ' 默认值-99999 APA status',
    PAS_ButtonPress	Bigint  comment ' 默认值-99999 RPA button press status',
    PAS_FLDistance	Bigint  comment ' 默认值-99999 Distance from front left sensor',
    PAS_FLMidDistance	Bigint  comment ' 默认值-99999 Distance from front left middle sensor',
    PAS_FRDistance	Bigint  comment ' 默认值-99999 Distance from front right sensor',
    PAS_FRMidDistance	Bigint  comment ' 默认值-99999 Distance from front right middle sensor',
    PAS_FrontObjExist	Bigint  comment ' 默认值-99999 POC function activation and then judgment w/wo front object',
    PAS_FSLSideDistance	Bigint  comment ' 默认值-99999 Distance from front left side sensor',
    PAS_FSRSideDistance	Bigint  comment ' 默认值-99999 Distance from front right side sensor',
    PAS_Mode	Bigint  comment ' 默认值-99999 Ultrasonic Sensor Working Mode',
    PAS_ParkSideSel	Bigint  comment ' 默认值-99999 Parking side selected',
    PAS_RLDistance	Bigint  comment ' 默认值-99999 Distance from rear left sensor',
    PAS_RLMidDistance	Bigint  comment ' 默认值-99999 Distance from rear left middle sensor',
    PAS_RRDistance	Bigint  comment ' 默认值-99999 Distance from rear right  sensor',
    PAS_RRMidDistance	Bigint  comment ' 默认值-99999 Distance from rear right middle sensor',
    PAS_RSLSideDistance	Bigint  comment ' 默认值-99999 Distance from rear left side sensor',
    PAS_RSRSideDistance	Bigint  comment ' 默认值-99999 Distance from rear right side sensor',
    PAS_SteeringAngleReqValue	DECIMAL(18, 8)  comment ' 默认值-99999 Requst to EPS(Electronic Power  Steering) to Steer wheel angle value.left is ‘-’(negative)  , right is+(positive)',
    PAS_SteeringCtrlReq	Bigint  comment ' 默认值-99999 Request to control EPS(Electronic Power  Steering)',
    PAS_SystemType	Bigint  comment ' 默认值-99999 PAS(Parking Assistant Sytem)  system type',
    PAS_WarnTone	Bigint  comment ' 默认值-99999 Warning tone',
    PCS_ACU_DisplayReq	Bigint  comment ' 默认值-99999 ACU display request',
    PCS_MMIAPAConfirmButton	Bigint  comment ' 默认值-99999 APA Confirm button',
    PCS_MMIAPAFuncSelect	Bigint  comment ' 默认值-99999 APA Function select',
    PCS_PASButtonPress	Bigint  comment ' 默认值-99999 PAS button press status',
    PEPS_EngForbidSt	Bigint  comment ' 默认值-99999 Engine forbid start state',
    PEPS_FobBattLowWarning	Bigint  comment ' 默认值-99999 FOB battery low warning',
    SAS_CalibratedSt	Bigint  comment ' 默认值-99999 the calibration information of steering angle sensor',
    SAS_SteeringAngle	DECIMAL(18, 8)  comment ' 默认值-99999 steering wheel angle',
    SAS_SteeringAngleSpd	Bigint  comment ' 默认值-99999 steering wheel angle speed',
    SAS_SteeringAngleVD	Bigint  comment ' 默认值-99999 SAS_SteeringAngle Valid Data',
    SRS_AirbagFaultSt	Bigint  comment ' 默认值-99999 To illuminate or turn off airbag warning indicator',
    SRS_CrashOutputSt	Bigint  comment ' 默认值-99999 To inform theres crash event happen in last 2sec.After 2 sec, the signal will turn to 0(crash here means any one of the 4 status defined above)',
    SRS_CrashOutputSt_Change	Bigint  comment ' 默认值-99999 nan',
    SRS_DriverSeatBeltSt	Bigint  comment ' 默认值-99999 To identify whether Driver Seat Belt is buckled',
    SRS_DriverSeatBeltSt_Change	Bigint  comment ' 默认值-99999 nan',
    SRS_PsngrSeatBeltSt	Bigint  comment ' 默认值-99999 To identify whether Passenger Seat Belt is buckled',
    SRS_PsngrSeatBeltSt_Change	Bigint  comment ' 默认值-99999 nan',
    TBOX_ACU_BookChrgMode	Bigint  comment ' 默认值-99999 the booking charge modeTBOX to ACU',
    TBOX_ACU_BookChrgStartDay	Bigint  comment ' 默认值-99999 the booking charge start day time TBOX to ACU',
    TBOX_ACU_BookChrgStartHour	Bigint  comment ' 默认值-99999 the booking charge start hour time TBOX to ACU',
    TBOX_ACU_BookChrgStartMin	Bigint  comment ' 默认值-99999 the booking charge start minune time TBOX to ACU',
    TBOX_ACU_BookChrgStartMon	Bigint  comment ' 默认值-99999 the booking charge start month time TBOX to ACU',
    TBOX_ACU_BookChrgStartYear	Bigint  comment ' 默认值-99999 the booking charge start year time TBOX to ACU',
    TBOX_ACU_BookChrgStopDay	Bigint  comment ' 默认值-99999 the booking charge stop day time TBOX to ACU',
    TBOX_ACU_BookChrgStopHour	Bigint  comment ' 默认值-99999 the booking charge stop hour time TBOX to ACU',
    TBOX_ACU_BookChrgStopMin	Bigint  comment ' 默认值-99999 the booking charge stop minune time TBOX to ACU',
    TBOX_ACU_BookChrgStopMon	Bigint  comment ' 默认值-99999 the booking charge stop month time TBOX to ACU',
    TBOX_ACU_BookChrgStopYear	Bigint  comment ' 默认值-99999 the booking charge start year time TBOX to ACU',
    TBOX_ACU_RepeatBookChrgDay1	Bigint  comment ' 默认值-99999 the repeat booking charge mode day1 TBOX to ACU',
    TBOX_ACU_RepeatBookChrgDay2	Bigint  comment ' 默认值-99999 the repeat booking charge mode day2 TBOX to ACU',
    TBOX_ACU_RepeatBookChrgDay3	Bigint  comment ' 默认值-99999 the repeat booking charge mode day3 TBOX to ACU',
    TBOX_ACU_RepeatBookChrgDay4	Bigint  comment ' 默认值-99999 the repeat booking charge mode day4 TBOX to ACU',
    TBOX_ACU_RepeatBookChrgDay5	Bigint  comment ' 默认值-99999 the repeat booking charge mode day5 TBOX to ACU',
    TBOX_ACU_RepeatBookChrgDay6	Bigint  comment ' 默认值-99999 the repeat booking charge mode day6 TBOX to ACU',
    TBOX_ACU_RepeatBookChrgDay7	Bigint  comment ' 默认值-99999 the repeat booking charge mode day7 TBOX to ACU',
    TEL_AltitudeType	Bigint  comment ' 默认值-99999 Altitude type',
    TEL_GPSAltitude	DECIMAL(18, 8)  comment ' 默认值-99999 Altitude,the unit of measuremen is meter',
    TEL_GPSDirection	DECIMAL(18, 8)  comment ' 默认值-99999 GPS device move direction',
    TEL_GPSSpeed	DECIMAL(18, 8)  comment ' 默认值-99999 GPS device move speed',
    TEL_HomeInd	Bigint  comment ' 默认值-99999 Home Indication',
    TEL_LatitudeDeg	Bigint  comment ' 默认值-99999 Latitude, the unit of measurement is degree',
    TEL_LatitudeMin	Bigint  comment ' 默认值-99999 Latitude, the unit of measurement is minute',
    TEL_LatitudeMode	Bigint  comment ' 默认值-99999 Latitude mode',
    TEL_LatitudeSec	DECIMAL(18, 8)  comment ' 默认值-99999 Latitude, the unit of measurement is second',
    TEL_LocType	Bigint  comment ' 默认值-99999 Location type',
    TEL_LongitudeDeg	Bigint  comment ' 默认值-99999 Longitude, the unit of measurement is degree',
    TEL_LongitudeMin	Bigint  comment ' 默认值-99999 Longitude, the unit of measurement is minute',
    TEL_LongitudeMode	Bigint  comment ' 默认值-99999 Longitude mode',
    TEL_LongitudeSec	DECIMAL(18, 8)  comment ' 默认值-99999 Longitude, the unit of measurement is second',
    TEL_NaviPstVD	Bigint  comment ' 默认值-99999 Navigation position validity',
    TEL_Time_Day	Bigint  comment ' 默认值-99999 Day number',
    TEL_Time_Hour	Bigint  comment ' 默认值-99999 Hour number',
    TEL_Time_Min	Bigint  comment ' 默认值-99999 Minute number',
    TEL_Time_Month	Bigint  comment ' 默认值-99999 Month number',
    TEL_Time_Sec	Bigint  comment ' 默认值-99999 Second number',
    TEL_Time_Year	Bigint  comment ' 默认值-99999 Year number',
    VCU_AccDriverOrvd	Bigint  comment ' 默认值-99999 Indicating the torque demanded by the driver ishigher than the torque demanded by ACC.',
    VCU_AccElecECFail	Bigint  comment ' 默认值-99999 Indicate the error state of electronic engine control.',
    VCU_AcChPlgSt	Bigint  comment ' 默认值-99999 AC charge plug lock status',
    VCU_ActVehWheelTorq	Bigint  comment ' 默认值-99999 Actual effective engine torque on wheel level',
    VCU_aiTACChL1BD	DECIMAL(18, 8)  comment ' 默认值-99999 converted Analog Input(ai)',
    VCU_aiTACChNBD	DECIMAL(18, 8)  comment ' 默认值-99999 converted Analog Input(ai)',
    VCU_aiTAmbBD	DECIMAL(18, 8)  comment ' 默认值-99999 Ambient temperature',
    VCU_aiTDCChNegBD	DECIMAL(18, 8)  comment ' 默认值-99999 converted Analog Input(ai)',
    VCU_aiTDCChPosBD	DECIMAL(18, 8)  comment ' 默认值-99999 converted Analog Input(ai)',
    VCU_APA_Resp	Bigint  comment ' 默认值-99999 VCU response to APA if VCU is response the gearshif and torque request',
    VCU_APAAvailable	Bigint  comment ' 默认值-99999 Whether VCU is available for APA function',
    VCU_APAWheelTorqDriverReq	Bigint  comment ' 默认值-99999 The driver torque on wheel request to APA',
    VCU_ARBWarnNotice	Bigint  comment ' 默认值-99999 Anti-roll back warn notice',
    VCU_BattCoolPwrReq	Bigint  comment ' 默认值-99999 VCU request the power to compressor for coolling battery',
    VCU_BattSocUndrWarn	Bigint  comment ' 默认值-99999 BMS SOC low',
    VCU_BDC1ReqMovePosBD	DECIMAL(18, 8)  comment ' 默认值-99999 Control valve Valve position request',
    VCU_BDCRspPositionBD	DECIMAL(18, 8)  comment ' 默认值-99999 Control valve Current position',
    VCU_BMS_BatModeReq	Bigint  comment ' 默认值-99999 HV Battery mode requested by VCU',
    VCU_BMS_CoolantInTemp	DECIMAL(18, 8)  comment ' 默认值-99999 Coolant inlet temperature of HV Battery',
    VCU_BMS_CoolantOutTemp	DECIMAL(18, 8)  comment ' 默认值-99999 Coolant outlet temperature of HV Battery',
    VCU_BookChgLampInd	Bigint  comment ' 默认值-99999 Actual book charge state for display',
    VCU_BrkPedPst	DECIMAL(18, 8)  comment ' 默认值-99999 Current brake pedal position',
    VCU_BrkPedPstVD	Bigint  comment ' 默认值-99999 Current brake pedal position valid data',
    VCU_BrkVcuuPress	Bigint  comment ' 默认值-99999 Brake Vacuum Pressure(BVP=Atmospheric Pressure - Booster Inner Absolute Pressure）',
    VCU_BrkVcuuPressVD	Bigint  comment ' 默认值-99999 Brake Vacuum Pressure Valid Data',
    VCU_bWakeUpBD	Bigint  comment ' 默认值-99999 State of VCU wakeup',
    VCU_ChgSOCResp	Bigint  comment ' 默认值-99999 Charge SOC response of HV battery to DVD for display',
    VCU_ChgTimeDspType	Bigint  comment ' 默认值-99999 Charging state for time display',
    VCU_CoolFanSpeedReq	Bigint  comment ' 默认值-99999 Cool fan Speed % request',
    VCU_CosStNmBusEnBD	Bigint  comment ' 默认值-99999 Require of VCU networkmanagement',
    VCU_CrntGearLvl	Bigint  comment ' 默认值-99999 VCU current carry out gear level',
    VCU_CrntGearLvlVD	Bigint  comment ' 默认值-99999 Valid bit for ActualGearPosition.',
    VCU_CtrlPwmDucycLT	Bigint  comment ' 默认值-99999 Duty Cycle(Ducyc) to control LT Pump',
    VCU_CtrlPwmDucycMT	Bigint  comment ' 默认值-99999 Duty Cycle(Ducyc) to control MT Pump',
    VCU_DcChgCurrOutReq	DECIMAL(18, 8)  comment ' 默认值-99999 Required DC charger output current',
    VCU_DCU_ActRotSpdFA	Bigint  comment ' 默认值-99999 Actual front e-motor rotation speed DCU',
    VCU_DCU_CoolantTemp	Bigint  comment ' 默认值-99999 Estimated IDU inlet coolant temperature',
    VCU_DCU_IdcMax	Bigint  comment ' 默认值-99999 max current for drive torque',
    VCU_DCU_ModeReq	Bigint  comment ' 默认值-99999 requestable state/mode of drive motor',
    VCU_DCU_SurgeDamperStReq	Bigint  comment ' 默认值-99999 Desired state for damping control feature',
    VCU_DCU_TorqSet	Bigint  comment ' 默认值-99999 target torque for drive motor',
    VCU_DiagLTPump	Bigint  comment ' 默认值-99999 Diagnostic information of  LT Pump',
    VCU_DiagMTPump	Bigint  comment ' 默认值-99999 Diagnostic information of MT Pump',
    VCU_diLock1BD	Bigint  comment ' 默认值-99999 Digital Input(di) Signal',
    VCU_diLock2BD	Bigint  comment ' 默认值-99999 Digital Input(di) Signal',
    VCU_DischgSocResp	Bigint  comment ' 默认值-99999 Discharge SOC response for display',
    VCU_doVacPmpEnBD	Bigint  comment ' 默认值-99999 Enable Vacuum Pump',
    VCU_DspChgCurr	DECIMAL(18, 8)  comment ' 默认值-99999 Display charge current',
    VCU_DspChgSt	Bigint  comment ' 默认值-99999 Display charge state',
    VCU_DspChgVolt	Bigint  comment ' 默认值-99999 Display charge voltage',
    VCU_DspDischgCurr	DECIMAL(18, 8)  comment ' 默认值-99999 Display discharge current',
    VCU_DspDischgSt	Bigint  comment ' 默认值-99999 Display discharge state',
    VCU_DspDischgVolt	Bigint  comment ' 默认值-99999 Display discharge voltage',
    VCU_EdvStBD	Bigint  comment ' 默认值-99999 VCU EDV state',
    VCU_ElcVcuuPumpErr	Bigint  comment ' 默认值-99999 Electric vacuum pump error',
    VCU_EM3To2ValveEn	Bigint  comment ' 默认值-99999 EM 3/2 way valve control state. (Disable = not passthe EM; Enable = pass the EM)',
    VCU_EMS_ACCButtInfo	Bigint  comment ' 默认值-99999 ACC Button Information',
    VCU_EMS_AccPedalActPst	DECIMAL(18, 8)  comment ' 默认值-99999 Current accelerate pedal actual position（Including the virtual  pedal）',
    VCU_EMS_AccPedalActPstVD	Bigint  comment ' 默认值-99999 Current accelerate pedal actual position validity',
    VCU_EMS_BrkNomalCloseSwitchSt	Bigint  comment ' 默认值-99999 Brake Pedal Normally Closed Switch Status',
    VCU_EMS_BrkPedalSt	Bigint  comment ' 默认值-99999 Brake pedal status',
    VCU_EMS_BrkPedalStVD	Bigint  comment ' 默认值-99999 VCU_EMS_BrakePedSt valid data',
    VCU_EpcbSysEmAfterRunBD	Bigint  comment ' 默认值-99999 EM afterrun state',
    VCU_ErhStBD	Bigint  comment ' 默认值-99999 VCU ERH state',
    VCU_EspDrvModReq	Bigint  comment ' 默认值-99999 Drive mode request to ESP',
    VCU_EVPRepair	Bigint  comment ' 默认值-99999 Warning for display,when EVP worked more than1450h.',
    VCU_EVPTime	Bigint  comment ' 默认值-99999 The time of EVP which worked',
    VCU_FaultLampInd	Bigint  comment ' 默认值-99999 HEV system error warning indictor',
    VCU_GearLvlDisp	Bigint  comment ' 默认值-99999 Gear lever for display',
    VCU_HVAC_BattCoolInTargetTemp	Bigint  comment ' 默认值-99999 Target demand for coolant temperature of battery in water pipe circuit',
    VCU_HVACEcoModeReq	Bigint  comment ' 默认值-99999 HVAC Eco mode request from VCU(EV/PHEV)',
    VCU_HVACPwrLimit	Bigint  comment ' 默认值-99999 Power limit of HVAC system by VCU (PTC+ECP total)',
    VCU_HVACPwrLimitAct	Bigint  comment ' 默认值-99999 Power limit active status of HVAC system by VCU(PTC+ECP total)',
    VCU_HVBatCoolPrioReq	Bigint  comment ' 默认值-99999 HVBat cool down climatization prioritization request',
    VCU_HVBatHeatPrioReq	Bigint  comment ' 默认值-99999 HVBat heat up climatization prioritization request',
    VCU_HvBatPrecdng	Bigint  comment ' 默认值-99999 HV battery preconditioning status for remote functions',
    VCU_HvBattFastCoolingSt	Bigint  comment ' 默认值-99999 VCU detection HV batt fast cooling  systerm work status',
    VCU_HVHDutyCycleBD	Bigint  comment ' 默认值-99999 HV_PTC Duty Cycle Actual',
    VCU_HVHHVDCCurrBD	Bigint  comment ' 默认值-99999 HV_PTC Current Draw of HV-PTC',
    VCU_HVHHVVoltageBD	Bigint  comment ' 默认值-99999 HV_PTC High Voltage Measurement',
    VCU_HVHStatusBD	Bigint  comment ' 默认值-99999 HV-PTC Status signals',
    VCU_HvilSt	Bigint  comment ' 默认值-99999 HVIL status',
    VCU_HVPTCHeatPecBD	Bigint  comment ' 默认值-99999 Heating Power Request in percent',
    VCU_HVPTCOnReqBD	Bigint  comment ' 默认值-99999 Enable Operation of HV-PTC',
    VCU_HVPwrUpErrStBD	Bigint  comment ' 默认值-99999 VCU power up failed status',
    VCU_HVVMediumTempBD	Bigint  comment ' 默认值-99999 HV_PTC Medium Temperature',
    VCU_ICM_RecActSt	Bigint  comment ' 默认值-99999 VCU judge actual recuperation activation status(Epadel recuperation, and if necessary, use this signal for epedal and RBS recuperation)',
    VCU_IpedalCreepCfgResp	Bigint  comment ' 默认值-99999 Response of the creep control status when Ipedal on',
    VCU_IPS_DCDCModeReq	Bigint  comment ' 默认值-99999 requestable target mode for DCDC',
    VCU_IPS_DCDCVoltLvSet	DECIMAL(18, 8)  comment ' 默认值-99999 requestable target output DC voltage at LV of DCDC',
    VCU_IPS_OBCChgCurrReq	DECIMAL(18, 8)  comment ' 默认值-99999 Required AC charge current  from IPS_OBC',
    VCU_IPS_OBCChgVoltReq	DECIMAL(18, 8)  comment ' 默认值-99999 Required AC charge valtage from IPS_OBC',
    VCU_IPS_OBCDsChDCCurrLim	DECIMAL(18, 8)  comment ' 默认值-99999 max allowed (limit) discharging current on DC side of OBC',
    VCU_IPS_OBCModeReq	Bigint  comment ' 默认值-99999 OBC mode request (0: no request, sleep indication allowed)',
    VCU_LateralAssistBtnInfo	Bigint  comment ' 默认值-99999 Lateral assist button Information',
    VCU_LateralAssistBtnInfoVD	Bigint  comment ' 默认值-99999 Lateral assist button Information valid data',
    VCU_LongDistResp	Bigint  comment ' 默认值-99999 Long Distance response for display',
    VCU_LVBatMntnSt	Bigint  comment ' 默认值-99999 LV battery maintenance status for remote functions',
    VCU_MaxRecpTorqFA	Bigint  comment ' 默认值-99999 Current front axel maximum available recuperation torque of generator',
    VCU_MaxRecpTorqFAVD	Bigint  comment ' 默认值-99999 Status of current front axel maximum availablerecuperation torque of generator',
    VCU_MaxVehTorqNormFA	Bigint  comment ' 默认值-99999 Max vehicle torque normal for front axle',
    VCU_ParkingReqToEPB	Bigint  comment ' 默认值-99999 Indicates the release/lock brake request to EPB',
    VCU_ParkingReqToEPBVD	Bigint  comment ' 默认值-99999 Indicates the release/lock brake request to EPB validdata',
    VCU_pAtmospheric	DECIMAL(18, 8)  comment ' 默认值-99999 baisc pressure',
    VCU_PlgConnSt	Bigint  comment ' 默认值-99999 Charge connector  connected Status',
    VCU_PwrCoolEn	Bigint  comment ' 默认值-99999 Activation flag for battery chiller',
    VCU_PwrHeatEn	Bigint  comment ' 默认值-99999 Activation flag for battery  heating',
    VCU_RecpActvStNotice	Bigint  comment ' 默认值-99999 Vehicle recuperation active state notice on ICM',
    VCU_RecpLevelstResp	Bigint  comment ' 默认值-99999 Response the recuperation level status',
    VCU_RecpTorqFA	Bigint  comment ' 默认值-99999 Current front axel recuperation torque of generator',
    VCU_RecpTorqFAVD	Bigint  comment ' 默认值-99999 Status of front axel recuperation torque of generator',
    VCU_RegenModulationReq	Bigint  comment ' 默认值-99999 The Regen modulation requirement from VCU',
    VCU_Released	Bigint  comment ' 默认值-99999 VCU released after decode',
    VCU_RemoteReleased	Bigint  comment ' 默认值-99999 VCU released remote function after decode',
    VCU_StACCBD	Bigint  comment ' 默认值-99999 VCU response to ACC',
    VCU_StAPABD	Bigint  comment ' 默认值-99999 VCU response to APA',
    VCU_stChcBD	Bigint  comment ' 默认值-99999 State of Charge in VCU',
    VCU_stDhcBD	Bigint  comment ' 默认值-99999 State of DisCharge in VCU',
    VCU_StNetMngtReqACANBD	Bigint  comment ' 默认值-99999 VCU request ACAN or not',
    VCU_StNetMngtReqBCANBD	Bigint  comment ' 默认值-99999 VCU request BCAN or not',
    VCU_StNetMngtReqECANBD	Bigint  comment ' 默认值-99999 VCU request ECAN or not',
    VCU_StNetMngtReqPCANBD	Bigint  comment ' 默认值-99999 VCU request PCAN or not',
    VCU_stSupBD	Bigint  comment ' 默认值-99999 State of Power Up and Down',
    VCU_stTempManageBD	Bigint  comment ' 默认值-99999 State of Thermal Control',
    VCU_TargetRecpTorqFA	Bigint  comment ' 默认值-99999 Current target recuperation torque of generator forfront axel',
    VCU_TargetRecpTorqFAVD	Bigint  comment ' 默认值-99999 Status of  Target cuperation torque of generator forfront axel',
    VCU_ThermalMsgWarn	Bigint  comment ' 默认值-99999 Thermal system has something wrong( inclue, MTpump,LT pumt, value,EXV, e.g.)，VCU give messages warn on ICM',
    VCU_TorqDriverReqFA	DECIMAL(18, 8)  comment ' 默认值-99999 The driver torque request for front axel',
    VCU_VacSensorErr	Bigint  comment ' 默认值-99999 Vacuum Pump Pressure Sensor Error Status',
    VCU_VehActDrvTorqFA	DECIMAL(18, 8)  comment ' 默认值-99999 Vehicle actual drive torque for front axel',
    VCU_VehActDrvTorqFAVD	Bigint  comment ' 默认值-99999 Vehicle actual drive torque valid data for front axel',
    VCU_VehChgDischgSt	Bigint  comment ' 默认值-99999 Traction Battery Charging and Discharging Status for Display',
    VCU_VehCrusSt	Bigint  comment ' 默认值-99999 Cruise Control State for display',
    VCU_VehCrusTgtSpd	Bigint  comment ' 默认值-99999 VCU set Cruise target speed for display(use ICM speed)',
    VCU_VehDrvMod	Bigint  comment ' 默认值-99999 Drive mode for display',
    VCU_VehElcConspAccumAvg	DECIMAL(18, 8)  comment ' 默认值-99999 Accumulated average electric consumption',
    VCU_VehElcConspAvg	DECIMAL(18, 8)  comment ' 默认值-99999 Average electric consumption',
    VCU_VehRdySt	Bigint  comment ' 默认值-99999 HEV system ready status',
    VCU_VehRng	Bigint  comment ' 默认值-99999 Total range for display',
    VCU_VehRngUndrWarn	Bigint  comment ' 默认值-99999 Total range low',
    VCU_VehWheelTorqMax	Bigint  comment ' 默认值-99999 Actual effective maximum adjustable torque on wheel level',
    VCU_WarmSt	Bigint  comment ' 默认值-99999 Warm time status',
    VCU_WarmTimeCfgResp	Bigint  comment ' 默认值-99999 Response of Warm time configuration respond',
    dt	Date
) with (
 'connector' = 'clickhouse',
    'url' = 'clickhouse://172.26.112.212:8123',
    'database-name' = 'ods_enterprise',
    'table-name' = 'g05_enterprise_tel_ul_tx',
    'sink.batch-size' = '20000',
    'sink.flush-interval' = '30000',
    'sink.max-retries' = '3',
	'username'='ck_admin',
	'password'='Gacnio-wlzx@2021',
	'use-local'='true'
);

create table g05_new_ck_kafka_enterprise_tel_ul_tx (
sampleTime string,
vehicleModelCode string,
vin string,
vin_mask string,
vehicleSeries string,
msgType string,
ptTime string,
dataList row<
ACU_AEBOff	string,
ACU_AVHSoftSwitchst	string,
ACU_CurrentSource	string,
ACU_DragModeReq	string,
ACU_EPBSwitchSt	string,
ACU_EPSStyleCfg	string,
ACU_FCWOff	string,
ACU_FCWWarnDistanceCfg	string,
ACU_HMA_SwitchReq	string,
ACU_iACC_SwitchReq	string,
ACU_IFC_ISDRestOfdis	string,
ACU_IFC_NaviCorp	string,
ACU_IFC_NaviNewIcon	string,
ACU_IFC_NaviNewIconDis	string,
ACU_IFC_NaviSt	string,
ACU_IFC_OfframpDis	string,
ACU_IFC_OfframpSt	string,
ACU_IFC_RoadType	string,
ACU_IFC_SLCAheadDis	string,
ACU_IFC_SpeedLimit	string,
ACU_IFC_SpeedLimtType	string,
ACU_Latitude	string,
ACU_LDW_LKACfg	string,
ACU_LKS_TypeReq	string,
ACU_Longitude	string,
ACU_TSR_AudioWarnReq	string,
ACU_TSR_SwitchReq	string,
ADAS_AdjLLnMrkingDispSt	string,
ADAS_AdjRLnMrkingDispSt	string,
ADAS_LLnMarkingDisPropToLnWidth	string,
ADAS_LLnMarkingType	string,
ADAS_LlnMrkingDispSt	string,
ADAS_LLnMrkingPolyCoeffA0	string,
ADAS_LLnMrkingPolyCoeffA1	string,
ADAS_LLnMrkingPolyCoeffA2	string,
ADAS_LnMarkingCurvature	string,
ADAS_LnMarkingHeadAngToVeh	string,
ADAS_RLnMarkingType	string,
ADAS_RlnMrkingDispSt	string,
ADAS_RLnMrkingPolyCoeffA0	string,
ADAS_RLnMrkingPolyCoeffA1	string,
ADAS_RLnMrkingPolyCoeffA2	string,
ADAS_TrkTargt0latPos	string,
ADAS_TrkTargt0longPos	string,
ADAS_TrkTargt0ObjClass	string,
ADAS_TrkTargt0St	string,
ADAS_TrkTargt1latPos	string,
ADAS_TrkTargt1longPos	string,
ADAS_TrkTargt1ObjClass	string,
ADAS_TrkTargt1St	string,
ADAS_TrkTargt2latPos	string,
ADAS_TrkTargt2longPos	string,
ADAS_TrkTargt2ObjClass	string,
ADAS_TrkTargt2St	string,
ADAS_TrkTargt3latPos	string,
ADAS_TrkTargt3longPos	string,
ADAS_TrkTargt3ObjClass	string,
ADAS_TrkTargt3St	string,
BCM_AlarmHistory	string,
BCM_ATWS_St	string,
BCM_AutoLightCtrlSt	string,
BCM_AutoLightSnsCfgSt	string,
BCM_AutoUnlockCfgSt	string,
BCM_BeamSwitchSt	string,
BCM_BonnetAjarSt	string,
BCM_BonnetAjarSt_Change	string,
BCM_BrakeLightFaultSt	string,
BCM_BrakeLightSt	string,
BCM_BrakeLightSwitchSt	string,
BCM_CentralLockSWSt	string,
BCM_DriverDoorAjarSt	string,
BCM_DriverDoorAjarSt_Change	string,
BCM_DriverDoorLockSt	string,
BCM_DriverDoorLockSt_Change	string,
BCM_DRLLFaultSt	string,
BCM_DRLRFaultSt	string,
BCM_DTRLFuncCfgSt	string,
BCM_DTRLSt	string,
BCM_ETWS_St	string,
BCM_FLWinSt	string,
BCM_FLWinSt_Change	string,
BCM_FOB_ID	string,
BCM_FogLampTurnCfgSt	string,
BCM_FrontFogLampSt	string,
BCM_FrontFogLampSt_Change	string,
BCM_FrontWasherSt	string,
BCM_FrontWasherSt_Change	string,
BCM_FrontWiperSt	string,
BCM_FRWinSt	string,
BCM_FRWinSt_Change	string,
BCM_HazardLampSt	string,
BCM_HighBeamSt	string,
BCM_IGNOffTime	string,
BCM_KeyInReminderWarnReq	string,
BCM_KeySt	string,
BCM_LampOnWarningReq	string,
BCM_LeftTurnLampFaultSt	string,
BCM_LeftTurnLampSt	string,
BCM_LeftTurnLampSt_Change	string,
BCM_LowBeamSt	string,
BCM_ParkingLampSt	string,
BCM_ParkingLampSt_Change	string,
BCM_PowerWinOpenWarn	string,
BCM_PsngrDoorAjarSt	string,
BCM_PsngrDoorAjarSt_Change	string,
BCM_PsngrDoorLockSt	string,
BCM_PsngrDoorLockSt_Change	string,
BCM_RearFogLampSt	string,
BCM_RearFogLampSt_Change	string,
BCM_RemoteControlSt	string,
BCM_ReverseLightSt	string,
BCM_ReverseSwitchSt	string,
BCM_RightTurnLampFaultSt	string,
BCM_RightTurnLampSt	string,
BCM_RightTurnLampSt_Change	string,
BCM_RLDoorAjarSt	string,
BCM_RLDoorAjarSt_Change	string,
BCM_RLSWarning_Light	string,
BCM_RLSWarning_Rain	string,
BCM_RLWinSt	string,
BCM_RLWinSt_Change	string,
BCM_RmtCtrlFobBattLow	string,
BCM_RoomlampSt	string,
BCM_RRDoorAjarSt	string,
BCM_RRDoorAjarSt_Change	string,
BCM_RRWinSt	string,
BCM_RRWinSt_Change	string,
BCM_SpdAutoLockCfgSt	string,
BCM_SunRoofOpenWarning	string,
BCM_SunRoofPstSt	string,
BCM_SunRoofPstSt_Change	string,
BCM_TransportModeSt	string,
BCM_TrunkAjarSt	string,
BCM_TrunkAjarSt_Change	string,
BCM_TurnLightSwitchSt	string,
BCM_VehReverseSt	string,
BCM_WinMoveSt	string,
BCS_ABAactive	string,
BCS_ABAavailable	string,
BCS_ABPActive	string,
BCS_ABPAvailable	string,
BCS_ABSActiveSt	string,
BCS_ABSFaultSt	string,
BCS_ActVehLaltrlAccel	string,
BCS_ActVehLaltrlAccelVD	string,
BCS_ActVehLongAccel	string,
BCS_ActVehLongAccelVD	string,
BCS_AEBActive	string,
BCS_AEBAvailable	string,
BCS_APAGrarLvlReq	string,
BCS_APAGrarLvlReqVD	string,
BCS_APALongContrAvail	string,
BCS_APALongContrFailSt	string,
BCS_APALongContrSt	string,
BCS_APATorqReqEV	string,
BCS_APATorqReqSt	string,
BCS_AVHAvailable	string,
BCS_AVHSoftSwctrlst	string,
BCS_AVHSt	string,
BCS_AVHStandby	string,
BCS_AVHSwitchSt	string,
BCS_AWBActive	string,
BCS_AWBAvailable	string,
BCS_BrakeOverHeat	string,
BCS_CDDActive	string,
BCS_CDDAvailable	string,
BCS_CDDFail	string,
BCS_CDPAvailable	string,
BCS_CDPIntervention	string,
BCS_CrbsActive	string,
BCS_EBDActiveSt	string,
BCS_EBDFaultSt	string,
BCS_EngTorqDecFastFA	string,
BCS_EngTorqInc	string,
BCS_EPBDragMode	string,
BCS_ESPFuncResp	string,
BCS_ExterBrkReqTargetVolFlow	string,
BCS_FLWheelRotatedDirection	string,
BCS_FLWheelRotatedDirectionAPA	string,
BCS_FLWheelRotatedDirectionVD	string,
BCS_FLWheelSpd	string,
BCS_FLWheelSpdVD	string,
BCS_FRWheelRotatedDirection	string,
BCS_FRWheelRotatedDirectionAPA	string,
BCS_FRWheelRotatedDirectionVD	string,
BCS_FRWheelSpd	string,
BCS_FRWheelSpdVD	string,
BCS_HBBIntervention	string,
BCS_HBBStatus	string,
BCS_HDCCtrlSt	string,
BCS_HDCErrSt	string,
BCS_HHCCtrlSt	string,
BCS_HHCErrSt	string,
BCS_MasterCylinderPr	string,
BCS_MasterCylinderPres	string,
BCS_MasterCylinderPrOffset	string,
BCS_MasterCylinderPrOffsetVD	string,
BCS_MasterCylinderPrVD	string,
BCS_MaxEstimatedWheelPres	string,
BCS_NoBrakeForce	string,
BCS_ParkingReqToEPB	string,
BCS_PedalForceCompenasationSt	string,
BCS_QDCACC	string,
BCS_RegenModulationAvailable	string,
BCS_RegenModuleActive	string,
BCS_RLWheelRotatedDirection	string,
BCS_RLWheelRotatedDirectionAPA	string,
BCS_RLWheelRotatedDirectionVD	string,
BCS_RLWheelSpd	string,
BCS_RLWheelSpdVD	string,
BCS_RRWheelRotatedDirection	string,
BCS_RRWheelRotatedDirectionAPA	string,
BCS_RRWheelRotatedDirectionVD	string,
BCS_RRWheelSpd	string,
BCS_RRWheelSpdVD	string,
BCS_TargetRecpTorqRqFA	string,
BCS_TargetRecpTorqRqFASt	string,
BCS_TCSActiveSt	string,
BCS_TCSFaultSt	string,
BCS_TCSOff	string,
BCS_VDCActiveSt	string,
BCS_VDCFaultSt	string,
BCS_VDCOff	string,
BCS_VehicleStandStillSt	string,
BCS_VehLaltrlAccelOffset	string,
BCS_VehLongAccelOffset	string,
BCS_VehSpd	string,
BCS_VehSpdVD	string,
BCS_VrtMasterCylinderPresSt	string,
BCS_YawRate	string,
BCS_YawRateOffset	string,
BCS_YawRateSt	string,
BMS_12Volt	string,
BMS_AcChgCurrMax	string,
BMS_AcChgVoltMax	string,
BMS_BalExecutionStatus	string,
BMS_BattChgErr	string,
BMS_BattChgSt	string,
BMS_BattCurr	string,
BMS_BattSocAct	string,
BMS_BattSocDisp	string,
BMS_BattSoe	string,
BMS_BattSoh	string,
BMS_BattTempAvg	string,
BMS_BattTempMax	string,
BMS_BattTempMin	string,
BMS_BattTypeStBD	string,
BMS_BattVolt	string,
BMS_BusVoltBD	string,
BMS_CellVoltAvg	string,
BMS_CellVoltMax	string,
BMS_CellVoltMin	string,
BMS_CellVoltSumBD	string,
BMS_ChgComplRemHour	string,
BMS_ChgComplRemMinute	string,
BMS_ChgCurrMax_Contns	string,
BMS_ChgCurrMax_Peak	string,
BMS_ChgVoltMax_Contns	string,
BMS_ChgVoltMax_Peak	string,
BMS_CoolantFlowReq	string,
BMS_CoolantTargTemp	string,
BMS_DcChargerSt	string,
BMS_DcChgConfigSt	string,
BMS_DcChgCurrMax	string,
BMS_DcChgErrLvl	string,
BMS_DcChgInfoSt	string,
BMS_DcChgrCurrCap	string,
BMS_DcChgrErrInfo	string,
BMS_DcChgrVoltCap	string,
BMS_DcChgSt	string,
BMS_DcChgVoltMax	string,
BMS_DchgCurrMax_Contns	string,
BMS_DchgCurrMax_Peak	string,
BMS_DchgVoltMax_Contns	string,
BMS_DchgVoltMax_Peak	string,
BMS_DCVoltBD	string,
BMS_DiagErrCode	string,
BMS_EmgLineSt	string,
BMS_ErrID10BD	string,
BMS_ErrID1BD	string,
BMS_ErrID2BD	string,
BMS_ErrID3BD	string,
BMS_ErrID4BD	string,
BMS_ErrID5BD	string,
BMS_ErrID6BD	string,
BMS_ErrID7BD	string,
BMS_ErrID8BD	string,
BMS_ErrID9BD	string,
BMS_FaultLampInd	string,
BMS_HvBattCoolErrSt	string,
BMS_HVBattElec	string,
BMS_HVBattSt	string,
BMS_HvilSt	string,
BMS_InslRes	string,
BMS_InslSt	string,
BMS_LastTimeChgEnergy	string,
BMS_NegVoltBD	string,
BMS_PrecResOverTemp	string,
BMS_PwrDwnReq	string,
BMS_SVBD	string,
BMS_ThermalReq	string,
BMS_ThermalRunawayErr	string,
BMS_ThermalRunawayTS10BD	string,
BMS_ThermalRunawayTS11BD	string,
BMS_ThermalRunawayTS1BD	string,
BMS_ThermalRunawayTS2BD	string,
BMS_ThermalRunawayTS3BD	string,
BMS_ThermalRunawayTS4BD	string,
BMS_ThermalRunawayTS5BD	string,
BMS_ThermalRunawayTS6BD	string,
BMS_ThermalRunawayTS7BD	string,
BMS_ThermalRunawayTS8BD	string,
BMS_ThermalRunawayTS9BD	string,
BMS_TotalChgEnergy	string,
DCU_DiagErrCode	string,
DCU_FaultLampInd	string,
DCU_HvilSt	string,
DCU_IdcAct	string,
DCU_InvtTemp	string,
DCU_ModeSt	string,
DCU_RotSpdAct	string,
DCU_RotTemp	string,
DCU_StatTemp	string,
DCU_TempCoolant	string,
DCU_TorqAct	string,
DCU_UdcAct	string,
EBB_ActOutputRodTravel	string,
EBB_ActOutputRodTravelSt	string,
EBB_BCSReqBrkPedalApplied	string,
EBB_BCSReqBrkPedalAppliedSt	string,
EBB_BrkFxCpb	string,
EBB_BrkPedalModeCfgSt	string,
EBB_CompatibilityIndex	string,
EBB_ExterBrkReqDominate	string,
EBB_HBCReq	string,
EBB_OutputRodTravelDriverReq	string,
EBB_OutputRodTravelDriverReqSt	string,
EBB_WarnLamp	string,
EBS_BattCurrent	string,
EBS_BattQuiescentCurrent	string,
EBS_BattTemp	string,
EBS_BattVolt	string,
EBS_CurrentRange	string,
EBS_CurrentSt	string,
EBS_Q_Charge	string,
EBS_Q_Discharge	string,
EBS_SOC	string,
EBS_SOC_STATE	string,
EBS_SOFV_Restart	string,
EBS_SOFV_Restart_St	string,
EBS_SOFV_StopEnable	string,
EBS_SOFV_StopEnable_St	string,
EBS_SOH_COR	string,
EBS_SOH_COR_St	string,
EBS_SOH_LAM	string,
EBS_SOH_LAM_St	string,
EBS_SOH_SUL	string,
EBS_SOH_SUL_St	string,
EBS_TempSt	string,
EBS_VoltSt	string,
EMS_GasPedalActPstforMRR	string,
EMS_GasPedalActPstforMRRVD	string,
EPB_AchievedClampForce	string,
EPB_ActuatorSt_L	string,
EPB_ActuatorSt_R	string,
EPB_DynamicApplySt	string,
EPB_FailSt	string,
EPB_MotorCurrent_L	string,
EPB_MotorCurrent_R	string,
EPB_SwitchSt	string,
EPB_SwitchStVD	string,
EPB_SysSt	string,
EPS_ElecPowerConsumption	string,
EPS_ElecPowerConsumptionVD	string,
EPS_FunctionStyleSt	string,
EPS_HandsOffDetSt	string,
EPS_HandsOffDetStVD	string,
EPS_LKACtrlAbortFeedback	string,
EPS_LKACtrlDlvdValue	string,
EPS_LKACtrlDlvdValueVD	string,
EPS_LKACtrlSt	string,
EPS_PAS_AbortFeedback	string,
EPS_PAS_EpasFailed	string,
EPS_PAS_ReqFeedback	string,
EPS_SteeringAngle	string,
EPS_SteeringAngleSpd	string,
EPS_SteeringAngleSpdVD	string,
EPS_SteeringAngleVD	string,
EPS_SteeringModeSt	string,
EPS_StrngWhlTorq	string,
EPS_StrngWhlTorqVD	string,
EPS_WarnLamp	string,
FAPA_APAActFuncInd	string,
FAPA_APAAuthst	string,
FAPA_LSMSubMTLevel	string,
FAPA_LSMSubMTLong	string,
FAPA_LSMSubMTReq	string,
FAPA_LSMVehDirRq	string,
FAPA_LSMVehSecReq	string,
FAPA_PASRemoteParkingEnable	string,
FAPA_PASRemoteParkingMode	string,
FLDCM_FLWinSt	string,
FLDCM_RLWinSt	string,
FRDCM_FRWinSt	string,
FRDCM_RRWinSt	string,
GSM_DriveMode	string,
GSM_GearShiftLeverPstReq	string,
HVAC_ACSt	string,
HVAC_AirCirculationSt	string,
HVAC_AirCompressorReq	string,
HVAC_AutoSt	string,
HVAC_CompressorSpdReq	string,
HVAC_CoolFanDutyCycleReq	string,
HVAC_CoolFanDutyCycleReqVD	string,
HVAC_CorrectedExterTemp	string,
HVAC_DisinfectenSt	string,
HVAC_DriverTempSelect	string,
HVAC_ECPFault	string,
HVAC_ECPPwrConsump	string,
HVAC_PsnTempSelect	string,
HVAC_PTCCoolantTemp	string,
HVAC_PTCFault	string,
HVAC_PTCPwrConsmp	string,
HVAC_RawCabinTemp	string,
HVAC_RawCabinTempVD	string,
HVAC_RawEvaTemp	string,
HVAC_RawExterTemp	string,
HVAC_RawExterTempVD	string,
HVAC_StsCabinCoolPrioReq	string,
HVAC_StsCabinHeatPrioReq	string,
HVAC_TelematicsSt	string,
HVAC_TempSelect	string,
HVAC_WindExitMode	string,
HVAC_WindExitSpd	string,
HVSM_FLHeatingActLevel	string,
HVSM_FLHVSMAutoModeSt	string,
HVSM_FLSeatTemp	string,
HVSM_FLSeatTempVD	string,
HVSM_FLVentilatingActLevel	string,
HVSM_FRHeatingActLevel	string,
HVSM_FRHVSMAutoModeSt	string,
HVSM_FRSeatTemp	string,
HVSM_FRSeatTempVD	string,
HVSM_FRVentilatingActLevel	string,
ICM_AvaibleDriveDistance	string,
ICM_BackLightLevel	string,
ICM_BattVolt	string,
ICM_BFLWarning	string,
ICM_DisFail	string,
ICM_SpdWarnCfgSt	string,
ICM_TotalOdometer	string,
ICM_TotalOdometer_accurate	string,
ICM_VehAverageSpd	string,
ICM_VehicleBrakeSt	string,
ICM_VehInsSpd	string,
ICM_VehRunningTime	string,
ICM_WFLWarning	string,
IFC_CameraBlockageSt	string,
IFC_ELKSt	string,
IFC_ELKWarnL	string,
IFC_ELKWarnR	string,
IFC_HMA_St	string,
IFC_HWAHF_HandsOnIcon	string,
IFC_LateralCtrlQuitWarn	string,
IFC_LeftTrackingSt	string,
IFC_LKS_LaneAssistType	string,
IFC_LKS_St	string,
IFC_LKS_TakeoverReq	string,
IFC_RightTrackingSt	string,
IFC_SysCalibrationSt	string,
IFC_TJA_ICA_St	string,
IFC_TorqueReq	string,
IFC_TorqueReqSt	string,
IFC_TSR_AudioWarnEnable	string,
IFC_TSR_OperatingSt	string,
IPS_ACHvilSt	string,
IPS_DCDC_KL15	string,
IPS_DCDC_KL30Volt	string,
IPS_DCDCCurrHvAct	string,
IPS_DCDCCurrLvAct	string,
IPS_DCDCDiagErrCode	string,
IPS_DCDCFaultLampInd	string,
IPS_DCDCFlowReq	string,
IPS_DCDCModeSt	string,
IPS_DCDCState1	string,
IPS_DCDCState2	string,
IPS_DCDCState3	string,
IPS_DCDCState4	string,
IPS_DCDCState5	string,
IPS_DCDCTempAct	string,
IPS_DCDCVoltHvAct	string,
IPS_DCDCVoltLvAct	string,
IPS_HVDCHVilSt	string,
IPS_OBCCC_Cap	string,
IPS_OBCCC_Res	string,
IPS_OBCCC_St	string,
IPS_OBCCp_DutyCycle	string,
IPS_OBCCpFreqSt	string,
IPS_OBCCpS2St	string,
IPS_OBCCPSt	string,
IPS_OBCCPVolt	string,
IPS_OBCCurrActL1	string,
IPS_OBCDiagErrCode	string,
IPS_OBCFaultLampInd	string,
IPS_OBCFlowReq	string,
IPS_OBCHvDcCurrAct	string,
IPS_OBCHvDcVoltAct	string,
IPS_OBCModeSt	string,
IPS_OBCState1	string,
IPS_OBCState2	string,
IPS_OBCState3	string,
IPS_OBCState4	string,
IPS_OBCState5	string,
IPS_OBCTempAct	string,
IPS_OBCUacActL1	string,
MRR_ABALevel	string,
MRR_ABAReq	string,
MRR_ABPReq	string,
MRR_ACCMode	string,
MRR_ACCRecpDecel	string,
MRR_ACCTakeOverReq	string,
MRR_ACCTextInfo	string,
MRR_ActTrqReq	string,
MRR_ActTrqReqVD	string,
MRR_AEB_PEDPFaultSt	string,
MRR_AEBDecelCtrlReq	string,
MRR_AEBFaultSt	string,
MRR_AEBInterventionSt	string,
MRR_AEBLVehHoldReq	string,
MRR_AEBOffSt	string,
MRR_AEBTargetDecel	string,
MRR_AWBLevel	string,
MRR_AWBReq	string,
MRR_FCWFaultSt	string,
MRR_FCWLatentWarn	string,
MRR_FCWOffSt	string,
MRR_FCWPreWarn	string,
MRR_FCWWarmDistance	string,
MRR_ISLACC_St	string,
MRR_LongCtrlAccelCtrlReq	string,
MRR_LongCtrlDecToStopReq	string,
MRR_LongCtrlDriveOff	string,
MRR_LongCtrlModeForBrkSys	string,
MRR_LongCtrlShutdownReq	string,
MRR_LongCtrlTargetAccel	string,
MRR_LongCtrlTargetAccelJerkMinValue	string,
MRR_LongCtrTargetAccelJerkMaxnValue	string,
MRR_ObjectCapturedSt	string,
MRR_PEBSObjType	string,
MRR_TauGapSet	string,
PAS_APA_ESPSpdLimit	string,
PAS_APA_ESPStopDist	string,
PAS_APAButtonPress	string,
PAS_APADrvReq	string,
PAS_APAModeInd	string,
PAS_APAParkslotSt	string,
PAS_APAQuitInd	string,
PAS_APARecInd	string,
PAS_APASt	string,
PAS_ButtonPress	string,
PAS_FLDistance	string,
PAS_FLMidDistance	string,
PAS_FRDistance	string,
PAS_FRMidDistance	string,
PAS_FrontObjExist	string,
PAS_FSLSideDistance	string,
PAS_FSRSideDistance	string,
PAS_Mode	string,
PAS_ParkSideSel	string,
PAS_RLDistance	string,
PAS_RLMidDistance	string,
PAS_RRDistance	string,
PAS_RRMidDistance	string,
PAS_RSLSideDistance	string,
PAS_RSRSideDistance	string,
PAS_SteeringAngleReqValue	string,
PAS_SteeringCtrlReq	string,
PAS_SystemType	string,
PAS_WarnTone	string,
PCS_ACU_DisplayReq	string,
PCS_MMIAPAConfirmButton	string,
PCS_MMIAPAFuncSelect	string,
PCS_PASButtonPress	string,
PEPS_EngForbidSt	string,
PEPS_FobBattLowWarning	string,
SAS_CalibratedSt	string,
SAS_SteeringAngle	string,
SAS_SteeringAngleSpd	string,
SAS_SteeringAngleVD	string,
SRS_AirbagFaultSt	string,
SRS_CrashOutputSt	string,
SRS_CrashOutputSt_Change	string,
SRS_DriverSeatBeltSt	string,
SRS_DriverSeatBeltSt_Change	string,
SRS_PsngrSeatBeltSt	string,
SRS_PsngrSeatBeltSt_Change	string,
TBOX_ACU_BookChrgMode	string,
TBOX_ACU_BookChrgStartDay	string,
TBOX_ACU_BookChrgStartHour	string,
TBOX_ACU_BookChrgStartMin	string,
TBOX_ACU_BookChrgStartMon	string,
TBOX_ACU_BookChrgStartYear	string,
TBOX_ACU_BookChrgStopDay	string,
TBOX_ACU_BookChrgStopHour	string,
TBOX_ACU_BookChrgStopMin	string,
TBOX_ACU_BookChrgStopMon	string,
TBOX_ACU_BookChrgStopYear	string,
TBOX_ACU_RepeatBookChrgDay1	string,
TBOX_ACU_RepeatBookChrgDay2	string,
TBOX_ACU_RepeatBookChrgDay3	string,
TBOX_ACU_RepeatBookChrgDay4	string,
TBOX_ACU_RepeatBookChrgDay5	string,
TBOX_ACU_RepeatBookChrgDay6	string,
TBOX_ACU_RepeatBookChrgDay7	string,
TEL_AltitudeType	string,
TEL_GPSAltitude	string,
TEL_GPSDirection	string,
TEL_GPSSpeed	string,
TEL_HomeInd	string,
TEL_LatitudeDeg	string,
TEL_LatitudeMin	string,
TEL_LatitudeMode	string,
TEL_LatitudeSec	string,
TEL_LocType	string,
TEL_LongitudeDeg	string,
TEL_LongitudeMin	string,
TEL_LongitudeMode	string,
TEL_LongitudeSec	string,
TEL_NaviPstVD	string,
TEL_Time_Day	string,
TEL_Time_Hour	string,
TEL_Time_Min	string,
TEL_Time_Month	string,
TEL_Time_Sec	string,
TEL_Time_Year	string,
VCU_AccDriverOrvd	string,
VCU_AccElecECFail	string,
VCU_AcChPlgSt	string,
VCU_ActVehWheelTorq	string,
VCU_aiTACChL1BD	string,
VCU_aiTACChNBD	string,
VCU_aiTAmbBD	string,
VCU_aiTDCChNegBD	string,
VCU_aiTDCChPosBD	string,
VCU_APA_Resp	string,
VCU_APAAvailable	string,
VCU_APAWheelTorqDriverReq	string,
VCU_ARBWarnNotice	string,
VCU_BattCoolPwrReq	string,
VCU_BattSocUndrWarn	string,
VCU_BDC1ReqMovePosBD	string,
VCU_BDCRspPositionBD	string,
VCU_BMS_BatModeReq	string,
VCU_BMS_CoolantInTemp	string,
VCU_BMS_CoolantOutTemp	string,
VCU_BookChgLampInd	string,
VCU_BrkPedPst	string,
VCU_BrkPedPstVD	string,
VCU_BrkVcuuPress	string,
VCU_BrkVcuuPressVD	string,
VCU_bWakeUpBD	string,
VCU_ChgSOCResp	string,
VCU_ChgTimeDspType	string,
VCU_CoolFanSpeedReq	string,
VCU_CosStNmBusEnBD	string,
VCU_CrntGearLvl	string,
VCU_CrntGearLvlVD	string,
VCU_CtrlPwmDucycLT	string,
VCU_CtrlPwmDucycMT	string,
VCU_DcChgCurrOutReq	string,
VCU_DCU_ActRotSpdFA	string,
VCU_DCU_CoolantTemp	string,
VCU_DCU_IdcMax	string,
VCU_DCU_ModeReq	string,
VCU_DCU_SurgeDamperStReq	string,
VCU_DCU_TorqSet	string,
VCU_DiagLTPump	string,
VCU_DiagMTPump	string,
VCU_diLock1BD	string,
VCU_diLock2BD	string,
VCU_DischgSocResp	string,
VCU_doVacPmpEnBD	string,
VCU_DspChgCurr	string,
VCU_DspChgSt	string,
VCU_DspChgVolt	string,
VCU_DspDischgCurr	string,
VCU_DspDischgSt	string,
VCU_DspDischgVolt	string,
VCU_EdvStBD	string,
VCU_ElcVcuuPumpErr	string,
VCU_EM3To2ValveEn	string,
VCU_EMS_ACCButtInfo	string,
VCU_EMS_AccPedalActPst	string,
VCU_EMS_AccPedalActPstVD	string,
VCU_EMS_BrkNomalCloseSwitchSt	string,
VCU_EMS_BrkPedalSt	string,
VCU_EMS_BrkPedalStVD	string,
VCU_EpcbSysEmAfterRunBD	string,
VCU_ErhStBD	string,
VCU_EspDrvModReq	string,
VCU_EVPRepair	string,
VCU_EVPTime	string,
VCU_FaultLampInd	string,
VCU_GearLvlDisp	string,
VCU_HVAC_BattCoolInTargetTemp	string,
VCU_HVACEcoModeReq	string,
VCU_HVACPwrLimit	string,
VCU_HVACPwrLimitAct	string,
VCU_HVBatCoolPrioReq	string,
VCU_HVBatHeatPrioReq	string,
VCU_HvBatPrecdng	string,
VCU_HvBattFastCoolingSt	string,
VCU_HVHDutyCycleBD	string,
VCU_HVHHVDCCurrBD	string,
VCU_HVHHVVoltageBD	string,
VCU_HVHStatusBD	string,
VCU_HvilSt	string,
VCU_HVPTCHeatPecBD	string,
VCU_HVPTCOnReqBD	string,
VCU_HVPwrUpErrStBD	string,
VCU_HVVMediumTempBD	string,
VCU_ICM_RecActSt	string,
VCU_IpedalCreepCfgResp	string,
VCU_IPS_DCDCModeReq	string,
VCU_IPS_DCDCVoltLvSet	string,
VCU_IPS_OBCChgCurrReq	string,
VCU_IPS_OBCChgVoltReq	string,
VCU_IPS_OBCDsChDCCurrLim	string,
VCU_IPS_OBCModeReq	string,
VCU_LateralAssistBtnInfo	string,
VCU_LateralAssistBtnInfoVD	string,
VCU_LongDistResp	string,
VCU_LVBatMntnSt	string,
VCU_MaxRecpTorqFA	string,
VCU_MaxRecpTorqFAVD	string,
VCU_MaxVehTorqNormFA	string,
VCU_ParkingReqToEPB	string,
VCU_ParkingReqToEPBVD	string,
VCU_pAtmospheric	string,
VCU_PlgConnSt	string,
VCU_PwrCoolEn	string,
VCU_PwrHeatEn	string,
VCU_RecpActvStNotice	string,
VCU_RecpLevelstResp	string,
VCU_RecpTorqFA	string,
VCU_RecpTorqFAVD	string,
VCU_RegenModulationReq	string,
VCU_Released	string,
VCU_RemoteReleased	string,
VCU_StACCBD	string,
VCU_StAPABD	string,
VCU_stChcBD	string,
VCU_stDhcBD	string,
VCU_StNetMngtReqACANBD	string,
VCU_StNetMngtReqBCANBD	string,
VCU_StNetMngtReqECANBD	string,
VCU_StNetMngtReqPCANBD	string,
VCU_stSupBD	string,
VCU_stTempManageBD	string,
VCU_TargetRecpTorqFA	string,
VCU_TargetRecpTorqFAVD	string,
VCU_ThermalMsgWarn	string,
VCU_TorqDriverReqFA	string,
VCU_VacSensorErr	string,
VCU_VehActDrvTorqFA	string,
VCU_VehActDrvTorqFAVD	string,
VCU_VehChgDischgSt	string,
VCU_VehCrusSt	string,
VCU_VehCrusTgtSpd	string,
VCU_VehDrvMod	string,
VCU_VehElcConspAccumAvg	string,
VCU_VehElcConspAvg	string,
VCU_VehRdySt	string,
VCU_VehRng	string,
VCU_VehRngUndrWarn	string,
VCU_VehWheelTorqMax	string,
VCU_WarmSt	string,
VCU_WarmTimeCfgResp	string>,
log_ts AS TO_TIMESTAMP (
FROM_UNIXTIME( CAST( sampleTime AS BIGINT )/ 1000, 'yyyy-MM-dd HH:mm:ss' )),
WATERMARK FOR log_ts AS log_ts - INTERVAL '5' SECOND
) WITH (
   'connector' = 'kafka',
  'topic' = 'hycan-period-compress',
  'properties.bootstrap.servers' = '${kafka.gb.bootstrap.servers}',
  'properties.group.id' = 'new_ck_enterprise_tel_ul_tx',
  'scan.startup.mode' = 'timestamp',
  'scan.startup.timestamp-millis' = '1650729600000',
  'format' = 'json',
   'scan.topic-partition-discovery.interval' = '5000'
);
