use ods_enterprise;
drop table if exists g05_enterprise_standard;
drop table if exists g05_kafka_enterprise_standard;
SET table.sql-dialect=hive;
create table g05_enterprise_standard
(
    id                             string comment '报文时间+VIN+报文类型;主键',
    receive_time                   timestamp comment '平台收到报文时间',
    message_time                   timestamp comment '报文时间',
    vin                            string comment '车辆VIN编码',
    message_type                   string comment '报文类型;1=车辆登入，2=实时信息上报，3=补发信息上报，4=车辆登出，5=平台登出',
    vehicle_status                 int comment '车辆状态;1=车辆启动状态，2=熄火，3=其他状态，254=表示异常，255=表示无效',
    charge_status                  int comment '充电状态;1=停车充电，2=行驶充电，3=未充电状态，4=充电完成，254=表示异常，255=表示无效',
    operation_mode                 int comment '运行模式;1= 纯电，2=混动，3=燃油，254=表示异常，255=表示无效',
    speed                          double comment '车速',
    mileage                        double comment '累计里程',
    total_volt                     double comment '总电压',
    total_current                  double comment '总电流',
    soc                            double comment 'SOC',
    dc_dc_status                   int comment 'DC-DC状态',
    gear                           int comment '挡位',
    insulation_resistance          int comment '绝缘电阻',
    accelerator_value              double comment '加速踏板行程值',
    brake_value                    double comment '制动踏板行程值',
    motor_sn_1                     int comment '1号驱动电机序号',
    status_1                       int comment '1号驱动电机状态',
    controller_temp_1              double comment '1号驱动电机控制器温度',
    rotation_speed_1               double comment '1号驱动电机转速',
    rotation_torque_1              double comment '1号驱动电机转矩',
    temp_1                         double comment '1号驱动电机温度',
    controller_in_volt_1           double comment '1号电机控制器输入电压',
    controller_dc_bus_current_1    double comment '1号电机控制器直流母线电流',
    motor_sn_2                     int comment '2号驱动电机序号',
    status_2                       int comment '2号驱动电机状态',
    controller_temp_2              double comment '2号驱动电机控制器温度',
    rotation_speed_2               double comment '2号驱动电机转速',
    rotation_torque_2              double comment '2号驱动电机转矩',
    temp_2                         double comment '2号驱动电机温度',
    controller_in_volt_2           double comment '2号电机控制器输入电压',
    controller_dc_bus_current_2    double comment '2号电机控制器直流母线电流',
    motor_sn_3                     int comment '3号驱动电机序号',
    status_3                       int comment '3号驱动电机状态',
    controller_temp_3              double comment '3号驱动电机控制器温度',
    rotation_speed_3               double comment '3号驱动电机转速',
    rotation_torque_3              double comment '3号驱动电机转矩',
    temp_3                         double comment '3号驱动电机温度',
    controller_in_volt_3           double comment '3号电机控制器输入电压',
    controller_dc_bus_current_3    double comment '3号电机控制器直流母线电流',
    motor_sn_4                     int comment '4号驱动电机序号',
    status_4                       int comment '4号驱动电机状态',
    controller_temp_4              double comment '4号驱动电机控制器温度',
    rotation_speed_4               double comment '4号驱动电机转速',
    rotation_torque_4              double comment '4号驱动电机转矩',
    temp_4                         double comment '4号驱动电机温度',
    controller_in_volt_4           double comment '4号电机控制器输入电压',
    controller_dc_bus_current_4    double comment '4号电机控制器直流母线电流',
    loaction_status                int comment '定位状态',
    loaction_longitude             string comment '经度',
    loaction_latitude              string comment '纬度',
    highest_volt_battery_pkg_sn    int comment '最高电压电池子系统号',
    highest_volt_cell_sn           int comment '最高电压电池单体代号',
    cell_highest_volt              double comment '电池单体电压最高值',
    lowest_volt_battery_pkg_sn     int comment '最低电压电池子系统号',
    lowest_volt_cell_sn            int comment '最低电压电池单体代号',
    cell_lowest_volt               double comment '电池单体电压最低值',
    highest_temp_battery_pkg_sn    int comment '最高温度子系统号',
    highest_temp_probe_sn          int comment '最高温度探针代号',
    highest_temp                   double comment '最高温度值',
    lowest_temp_battery_pkg_sn     int comment '最低温度子系统号',
    lowest_temp_probe_sn           int comment '最低温度探针序号',
    lowest_temp                    double comment '最低温度值',
	
    alarm_level                    int comment '报警等级;0=无故障;1=1级故障;2=2级故障;3=3级故障',
    alarm_flag                     STRING comment '通用报警标志',
	alarm_reess_fault_cnt          int comment '可充电储能装置故障总数；0：正常',
	reess_fault_list               string comment '可充电储能装置故障代码列表；0：正常',
	motor_fault_cnt                int comment '驱动电机故障总数；0：正常',
    motor_fault_list               string comment '驱动电机故障代码列表；0：正常',
	 engine_fault_cnt               int comment '发动机故障总数；0：正常',
    engine_fault_list              string comment '发动机故障代码列表；0：正常',
	other_fault_cnt                int comment '其他故障总数；0：正常',
    other_fault_list               string comment '其他故障代码列表；0：正常',
	
	baoJingBiaoZhiBinaryValue      string,
	alarmSize                      string,
	
	pressure_no      int comment 'dianyashuju',
	totalDianya      string comment 'dianyashuju',
	begCellSerialNo      int comment 'dianyashuju',
	totalDianliu      string comment 'dianyashuju',
	totalCellCount      int comment 'dianyashuju',
	bzdtdcCount      int comment 'dianyashuju',
	dianyaValues      string comment 'dianyashuju',
	
	temp_probe_count               int comment '温度探针个数',
    temp_probe_values              string comment '各温度探针检测到的温度值(°C)'

	
) PARTITIONED BY (dt STRING) STORED AS parquet TBLPROPERTIES (
    'partition.time-extractor.timestamp-pattern'='$dt',
    'sink.partition-commit.trigger'='partition-time',
    'sink.partition-commit.delay'='1 h',
    'sink.partition-commit.watermark-time-zone'='Asia/Shanghai',
    'sink.partition-commit.policy.kind'='metastore,success-file'
);

SET table.sql-dialect=default;
CREATE TABLE g05_kafka_enterprise_standard (
    zhengcheshuju array<row<signalValue STRING>>,
    dianyashuju array<row<`no` int,totalDianya STRING,begCellSerialNo int,totalDianliu STRING,totalCellCount int,bzdtdcCount int,dianyaValues STRING>>,
    qudongdianjishuju array<array<row<signalValue STRING>>>,
    gatherTime STRING,
    vin STRING,
    wendushuju array<row<probeCount int,wenduValues STRING>>,
    alarmSize STRING,
    jizhishuju array<row<signalValue STRING>>,
    baojingshuju array<row<signalValue STRING>>,
    baoJingBiaoZhiBinaryValue STRING,
    weizhishuju array<row<signalValue STRING>>,
    log_ts as TO_TIMESTAMP(FROM_UNIXTIME(CAST(gatherTime AS bigint)/1000, 'yyyy-MM-dd HH:mm:ss')),
    WATERMARK FOR log_ts AS log_ts - INTERVAL '5' SECOND
) WITH (
  'connector' = 'kafka',
  'topic' = 'hycan_report',
  'properties.bootstrap.servers' = '${kafka.gb.bootstrap.servers}',
  'properties.group.id' = 'enterprise_standard',
  'scan.startup.mode' = 'earliest-offset',
  'format' = 'json'
);