lexer grammar PrestoSqlLexer;

// ============================================
// 关键字定义（继承 Flink/Spark 基础）
// ============================================

KW_INSERT: 'INSERT';
KW_INTO: 'INTO';
KW_OVERWRITE: 'OVERWRITE';
KW_SELECT: 'SELECT';
KW_FROM: 'FROM';
KW_JOIN: 'JOIN';
KW_LEFT: 'LEFT';
KW_RIGHT: 'RIGHT';
KW_FULL: 'FULL';
KW_INNER: 'INNER';
KW_OUTER: 'OUTER';
KW_ON: 'ON';
KW_WHERE: 'WHERE';
KW_GROUP: 'GROUP';
KW_BY: 'BY';
KW_HAVING: 'HAVING';
KW_ORDER: 'ORDER';
KW_LIMIT: 'LIMIT';
KW_AS: 'AS';
KW_WITH: 'WITH';
KW_CREATE: 'CREATE';
KW_TABLE: 'TABLE';
KW_VIEW: 'VIEW';
KW_CAST: 'CAST';
KW_FUNCTION: 'FUNCTION';
KW_DISTINCT: 'DISTINCT';
KW_ALL: 'ALL';
KW_TRUE: 'TRUE';
KW_FALSE: 'FALSE';
KW_NULL: 'NULL';
KW_NOT: 'NOT';
KW_AND: 'AND';
KW_OR: 'OR';
KW_IS: 'IS';
KW_FOR: 'FOR';
KW_PARTITION: 'PARTITION';
KW_PRIMARY: 'PRIMARY';
KW_KEY: 'KEY';
KW_CONSTRAINT: 'CONSTRAINT';
KW_UNIQUE: 'UNIQUE';
KW_REFERENCES: 'REFERENCES';
KW_DEFAULT: 'DEFAULT';
KW_COMMENT: 'COMMENT';
KW_PRIMARY_KEY: 'PRIMARY KEY';
KW_UNBOUNDED: 'UNBOUNDED';
KW_PRECEDING: 'PRECEDING';
KW_FOLLOWING: 'FOLLOWING';
KW_CURRENT: 'CURRENT';
KW_ROW: 'ROW';
KW_ROWS: 'ROWS';
KW_RANGE: 'RANGE';
KW_BETWEEN: 'BETWEEN';
KW_IN: 'IN';
KW_UNION: 'UNION';
KW_INTERSECT: 'INTERSECT';
KW_EXCEPT: 'EXCEPT' | 'MINUS';
KW_DROP: 'DROP';
KW_ALTER: 'ALTER';

// ============================================
// Presto 特有关键字
// ============================================

KW_EXPLAIN: 'EXPLAIN';
KW_ANALYZE: 'ANALYZE';
KW_EXECUTE: 'EXECUTE';
KW_DEALLOCATE: 'DEALLOCATE';
KW_PREPARE: 'PREPARE';
KW_DESCRIBE: 'DESCRIBE';
KW_SHOW: 'SHOW';
KW_SET: 'SET';
KW_RESET: 'RESET';
KW_LOCK: 'LOCK';
KW_UNLOCK: 'UNLOCK';
KW_FLUSH: 'FLUSH';
KW_TRUNCATE: 'TRUNCATE';
KW_REPAIR: 'REPAIR';
KW_OPTIMIZE: 'OPTIMIZE';
KW_VACUUM: 'VACUUM';
KW_REFRESH: 'REFRESH';
KW_INVALIDATE: 'INVALIDATE';
KW_CACHE: 'CACHE';
KW_SYNC: 'SYNC';
KW_ASYNC: 'ASYNC';
KW_MANUAL: 'MANUAL';
KW_AUTOMATIC: 'AUTOMATIC';
KW_ENABLED: 'ENABLED';
KW_DISABLED: 'DISABLED';
KW_ROLLBACK: 'ROLLBACK';
KW_SAVEPOINT: 'SAVEPOINT';
KW_RELEASE: 'RELEASE';
KW_WORK: 'WORK';
KW_SESSION: 'SESSION';
KW_LOCAL: 'LOCAL';
KW_GLOBAL: 'GLOBAL';
KW_TRANSACTION: 'TRANSACTION';
KW_ISOLATION: 'ISOLATION';
KW_READ: 'READ';
KW_WRITE: 'WRITE';
KW_COMMIT: 'COMMIT';
KW_SERIALIZABLE: 'SERIALIZABLE';
KW_REPEATABLE: 'REPEATABLE';
KW_COMMITTED: 'COMMITTED';
KW_UNCOMMITTED: 'UNCOMMITTED';
KW_SNAPSHOT: 'SNAPSHOT';
KW_SCHEMA: 'SCHEMA';
KW_CATALOG: 'CATALOG';
KW_DATASOURCE: 'DATASOURCE';
KW_NODE: 'NODE';
KW_CLUSTER: 'CLUSTER';
KW_POOL: 'POOL';
KW_RESOURCE: 'RESOURCE';
KW_PRIORITY: 'PRIORITY';
KW_WEIGHT: 'WEIGHT';
KW_SOURCE: 'SOURCE';
KW_SINK: 'SINK';
KW_CONNECTOR: 'CONNECTOR';
KW_PROPERTIES: 'PROPERTIES';
KW_PROPERTY: 'PROPERTY';
KW_LOCATION: 'LOCATION';
KW_FORMAT: 'FORMAT';
KW_RECORD: 'RECORD';
KW_FIELD: 'FIELD';
KW_COLUMN: 'COLUMN';
// KW_SCHEMA: 已在第 112 行定义
KW_TYPE: 'TYPE';
KW_ENUM: 'ENUM';
KW_STRUCT: 'STRUCT';
KW_MAP: 'MAP';
KW_ARRAY: 'ARRAY';
// KW_ROW: 已在第 55 行定义
KW_DECIMAL: 'DECIMAL';
KW_DOUBLE: 'DOUBLE';
KW_REAL: 'REAL';
KW_FLOAT: 'FLOAT';
KW_BOOLEAN: 'BOOLEAN';
KW_TINYINT: 'TINYINT';
KW_SMALLINT: 'SMALLINT';
KW_INTEGER: 'INTEGER';
KW_INT: 'INT';
KW_BIGINT: 'BIGINT';
KW_VARBINARY: 'VARBINARY';
KW_CHAR: 'CHAR';
KW_VARCHAR: 'VARCHAR';
KW_JSON: 'JSON';
KW_IPADDRESS: 'IPADDRESS';
KW_UUID: 'UUID';
KW_TIME: 'TIME';
KW_TIMESTAMP: 'TIMESTAMP';
KW_DATE: 'DATE';
KW_INTERVAL: 'INTERVAL';
KW_REGEXP: 'REGEXP';
KW_PATTERN: 'PATTERN';
KW_SYNTAX: 'SYNTAX';
KW_ERROR: 'ERROR';
KW_MESSAGE: 'MESSAGE';
KW_LEVEL: 'LEVEL';
KW_MODULE: 'MODULE';
KW_NAME: 'NAME';
KW_VERSION: 'VERSION';
KW_DESCRIPTION: 'DESCRIPTION';
KW_CATEGORY: 'CATEGORY';
KW_TAGS: 'TAGS';
KW_OWNER: 'OWNER';
KW_CREATED_AT: 'CREATED_AT';
KW_MODIFIED_AT: 'MODIFIED_AT';
KW_STATISTICS: 'STATISTICS';
KW_METRICS: 'METRICS';
KW_SUMMARY: 'SUMMARY';
KW_DETAIL: 'DETAIL';
KW_PROFILES: 'PROFILES';
KW_DISTRIBUTION: 'DISTRIBUTION';
KW_SPLIT: 'SPLIT';
KW_FILE: 'FILE';
KW_FILES: 'FILES';
KW_PATH: 'PATH';
KW_URI: 'URI';
KW_URL: 'URL';
KW_PROTOCOL: 'PROTOCOL';
KW_HOST: 'HOST';
KW_PORT: 'PORT';
KW_DATABASE: 'DATABASE';
KW_CATALOG_NAME: 'CATALOG_NAME';
KW_SCHEMA_NAME: 'SCHEMA_NAME';
KW_TABLE_NAME: 'TABLE_NAME';
KW_COLUMN_NAME: 'COLUMN_NAME';
KW_COLUMN_LIST: 'COLUMN_LIST';
KW_TABLE_LIST: 'TABLE_LIST';
KW_SCHEMA_LIST: 'SCHEMA_LIST';
KW_CATALOG_LIST: 'CATALOG_LIST';
KW_FUNCTION_LIST: 'FUNCTION_LIST';
KW_PROCEDURE_LIST: 'PROCEDURE_LIST';
KW_GRANT: 'GRANT';
KW_REVOKE: 'REVOKE';
KW_ROLE: 'ROLE';
KW_USER: 'USER';
// KW_GROUP: 已在第 20 行定义
KW_PRINCIPAL: 'PRINCIPAL';
KW_PRIVILEGE: 'PRIVILEGE';
KW_PERMISSION: 'PERMISSION';
KW_ACCESS: 'ACCESS';
KW_CONTROL: 'CONTROL';
KW_ADMIN: 'ADMIN';
KW_MODIFY: 'MODIFY';
// KW_SELECT: 已在第 10 行定义
// KW_INSERT: 已在第 7 行定义
// KW_UPDATE: 已在前面定义
// KW_DELETE: 已在前面定义
// KW_DROP: 已在前面定义
// KW_QUERY: 已在前面定义
// KW_CREATE: 已在第 27 行定义
// KW_ALTER: 已在第 64 行定义
KW_USAGE: 'USAGE';
KW_TEMPORARY: 'TEMPORARY';
KW_TEMP: 'TEMP';
KW_UNLOGGED: 'UNLOGGED';
KW_SECURE: 'SECURE';
KW_INVOKER: 'INVOKER';
KW_DEFINER: 'DEFINER';
KW_RESTRICT: 'RESTRICT';
KW_CASCADE: 'CASCADE';
KW_FK: 'FK';
KW_PK: 'PK';
KW_UQ: 'UQ';
KW_NK: 'NK';
// KW_UNIQUE: 已在第 46 行定义
KW_CHECK: 'CHECK';
KW_CLUSTERED: 'CLUSTERED';
KW_NONCLUSTERED: 'NONCLUSTERED';
KW_INCLUDE: 'INCLUDE';
KW_FILLFACTOR: 'FILLFACTOR';
KW_PCTFREE: 'PCTFREE';
KW_PCTUSED: 'PCTUSED';
KW_THRESHOLD: 'THRESHOLD';
KW_OVERRIDING: 'OVERRIDING';
KW_SYSTEM: 'SYSTEM';
// KW_USER: 已在第 202 行定义
KW_OBJECT: 'OBJECT';
KW_IDENTIFIER: 'IDENTIFIER';
KW_LITERAL: 'LITERAL';
KW_PARAMETER: 'PARAMETER';
KW_EXPRESSION: 'EXPRESSION';
KW_CONDITION: 'CONDITION';
KW_STATEMENT: 'STATEMENT';
KW_BLOCK: 'BLOCK';
KW_SEQUENCE: 'SEQUENCE';
KW_TRIGGER: 'TRIGGER';
KW_EVENT: 'EVENT';
KW_SCHEDULER: 'SCHEDULER';
KW_JOB: 'JOB';
KW_TASK: 'TASK';
KW_STEP: 'STEP';
KW_PIPELINE: 'PIPELINE';
KW_STAGE: 'STAGE';
KW_PROCESSOR: 'PROCESSOR';
KW_CONSUMER: 'CONSUMER';
KW_PRODUCER: 'PRODUCER';
KW_SUBSCRIBER: 'SUBSCRIBER';
KW_PUBLISHER: 'PUBLISHER';
KW_TOPIC: 'TOPIC';
KW_CHANNEL: 'CHANNEL';
KW_QUEUE: 'QUEUE';
KW_STREAM: 'STREAM';
KW_BATCH: 'BATCH';
KW_MICROBATCH: 'MICROBATCH';
KW_WINDOW: 'WINDOW';
KW_SLIDING: 'SLIDING';
KW_TUMBLING: 'TUMBLING';
// KW_SESSION: 已在第 99 行定义
KW_TRIGGERED: 'TRIGGERED';
KW_WATERMARK: 'WATERMARK';
KW_LATENCY: 'LATENCY';
KW_THROUGHPUT: 'THROUGHPUT';
KW_BACKPRESSURE: 'BACKPRESSURE';
KW_FLOW: 'FLOW';
KW_RATE: 'RATE';
// KW_QUOTA: 'QUOTA';
// KW_LIMIT: 已在第 24 行定义
KW_MAX: 'MAX';
KW_MIN: 'MIN';
KW_AVG: 'AVG';
KW_SUM: 'SUM';
KW_COUNT: 'COUNT';
KW_FIRST: 'FIRST';
KW_LAST: 'LAST';
KW_HEAD: 'HEAD';
KW_TAIL: 'TAIL';
KW_SAMPLE: 'SAMPLE';
KW_RANDOM: 'RANDOM';
KW_DISTRIBUTE: 'DISTRIBUTE';
KW_SORT: 'SORT';
// KW_CLUSTER: 已在第 116 行定义
KW_SHARD: 'SHARD';
// KW_PARTITION: 已在第 42 行定义
KW_BUCKET: 'BUCKET';
KW_ZONE: 'ZONE';
KW_REGION: 'REGION';
KW_AZURE: 'AZURE';
KW_GCP: 'GCP';
KW_ALIYUN: 'ALIYUN';
KW_TENCENT: 'TENCENT';
// KW_HUAWEI: 已在第 308 行定义
KW_YANDEX: 'YANDEX';
KW_AWS: 'AWS';
KW_GOOGLE: 'GOOGLE';
KW_MICROSOFT: 'MICROSOFT';
KW_ALIBABA: 'ALIBABA';
KW_TENCCENT: 'TENCENT';
KW_HUAWEI: 'HUAWEI';

// ============================================
// 数据类型关键字
// ============================================

// KW_INT: 已在第 146 行定义
// KW_BIGINT: 已在第 147 行定义
// KW_SMALLINT: 已在第 144 行定义
// KW_TINYINT: 已在第 143 行定义
// KW_BOOLEAN: 已在第 142 行定义
// KW_DATE: 已在第 156 行定义
// KW_TIME: 已在前面定义
// KW_TIMESTAMP: 已在前面定义
// KW_BINARY: 已在前面定义
// KW_VARBINARY: 已在前面定义
// KW_ARRAY: 已在前面定义
// KW_MAP: 已在前面定义
// KW_ROW: 已在前面定义
KW_ANY: 'ANY';
// KW_JSON: 已在第 151 行定义
// KW_IPADDRESS: 已在第 152 行定义
// KW_UUID: 已在前面定义

// ============================================
// TVF (Table-valued Functions) - Presto 特有
// ============================================

KW_EXPLODE: 'EXPLODE';
KW_POSEXPLODE: 'POSEXPLODE';
KW_GENERATE_SUBSCRIPTS: 'GENERATE_SUBSCRIPTS';
KW_UNNEST: 'UNNEST';
KW_CARTESIAN_PRODUCT: 'CARTESIAN_PRODUCT';
KW_SIDWAYS: 'SIDWAYS';
KW_LATERAL: 'LATERAL';
KW_FLATTEN: 'FLATTEN';
KW_TRANSFORM: 'TRANSFORM';
KW_APPLY: 'APPLY';
KW_CALL: 'CALL';
KW_RUN: 'RUN';
KW_EXEC: 'EXEC';
KW_DO: 'DO';
KW_CASE: 'CASE';
KW_WHEN: 'WHEN';
KW_THEN: 'THEN';
KW_ELSE: 'ELSE';
KW_END: 'END';
KW_START: 'START';
KW_STOP: 'STOP';
KW_PAUSE: 'PAUSE';
KW_RESUME: 'RESUME';
KW_SUSPEND: 'SUSPEND';
KW_ACTIVE: 'ACTIVE';
KW_INACTIVE: 'INACTIVE';
KW_FAILED: 'FAILED';
KW_SUCCESS: 'SUCCESS';
KW_PENDING: 'PENDING';
KW_RUNNING: 'RUNNING';
KW_COMPLETED: 'COMPLETED';
KW_ABORTED: 'ABORTED';
KW_CANCELLED: 'CANCELLED';
KW_SKIPPED: 'SKIPPED';
KW_RETRY: 'RETRY';
KW_RECOVER: 'RECOVER';
KW_FAIL: 'FAIL';
KW_SUCCEED: 'SUCCEED';
KW_OK: 'OK';
KW_ERR: 'ERR';
KW_WARN: 'WARN';
KW_INFO: 'INFO';
KW_DEBUG: 'DEBUG';
KW_TRACE: 'TRACE';
KW_LOG: 'LOG';
KW_AUDIT: 'AUDIT';
KW_SECURITY: 'SECURITY';
KW_COMPLIANCE: 'COMPLIANCE';
KW_GOVERNANCE: 'GOVERNANCE';
KW_QUALITY: 'QUALITY';
KW_PERFORMANCE: 'PERFORMANCE';
KW_MONITORING: 'MONITORING';
KW_ALERTING: 'ALERTING';
KW_NOTIFICATION: 'NOTIFICATION';
KW_SUBSCRIPTION: 'SUBSCRIPTION';
KW_FEEDBACK: 'FEEDBACK';
KW_REVIEW: 'REVIEW';
KW_APPROVAL: 'APPROVAL';
KW_AUTHORIZATION: 'AUTHORIZATION';
KW_AUTHENTICATION: 'AUTHENTICATION';
KW_ENCRYPTION: 'ENCRYPTION';
KW_DECRYPTION: 'DECRYPTION';
KW_SIGNING: 'SIGNING';
KW_VERIFICATION: 'VERIFICATION';
KW_VALIDATION: 'VALIDATION';
KW_CERTIFICATION: 'CERTIFICATION';
KW_ACCREDITATION: 'ACCREDITATION';
KW_LICENSE: 'LICENSE';
KW_PERMIT: 'PERMIT';
KW_CERTIFICATE: 'CERTIFICATE';
// KW_KEY: 已在第 44 行定义
KW_SECRET: 'SECRET';
KW_TOKEN: 'TOKEN';
KW_CREDENTIAL: 'CREDENTIAL';
KW_PASSWORD: 'PASSWORD';
KW_PIN: 'PIN';
KW_CODE: 'CODE';
KW_CAPTCHA: 'CAPTCHA';
KW_MFA: 'MFA';
KW_2FA: '2FA';
KW_OTP: 'OTP';
KW_SSO: 'SSO';
KW_OIDC: 'OIDC';
KW_SAML: 'SAML';
KW_LDAP: 'LDAP';
KW_AD: 'AD';
KW_NIS: 'NIS';
KW_KERBEROS: 'KERBEROS';
// KW_RADIUS: 已在第 431 行定义
KW_TACACS: 'TACACS';

// ============================================
// 标识符
// ============================================

UID: [a-zA-Z_][a-zA-Z0-9_]*;
QUOTED_UID: '`' (~[`])+ '`';

// ============================================
// 字符串和数字
// ============================================

STRING: '\'' (~'\'')+ '\'';

NUMBER: [0-9]+;
DECIMAL_NUMBER: [0-9]+'.'[0-9]+;
EXP_NUMBER: [0-9]+[eE][+-]?[0-9]+;
HEX_NUMBER: '0[xX]' [0-9a-fA-F]+;
BIN_NUMBER: '0[bB]' [01]+;

// ============================================
// 运算符
// ============================================

PLUS: '+';
MINUS: '-';
MULT: '*';
DIV: '/';
MOD: '%';
EQ: '=';
NEQ: '<>' | '!=';
LT: '<';
GT: '>';
LTE: '<=';
GTE: '>=';
CONCAT: '||';
ARROW: '->';
LONG_ARROW: '=>';
COLON_ASSIGN: ':=';

// ============================================
// 标点符号
// ============================================

LPAREN: '(';
RPAREN: ')';
LBRACKET: '[';
RBRACKET: ']';
LBRACE: '{';
RBRACE: '}';
COMMA: ',';
COLON: ':';
DOT: '.';
SEMICOLON: ';';
AT: '@';
EXCLAMATION: '!';
QUESTION: '?';
STAR: '*';
AMPERSAND: '&';
BAR: '|';
CARET: '^';
TILDE: '~';
SLASH: '/';
BACKSLASH: '\\';
BACKTICK: '`';

// ============================================
// 空白字符（跳过）
// ============================================

WS: [ \t\r\n]+ -> skip;

// ============================================
// 注释
// ============================================

LINE_COMMENT: '--' ~[\r\n]* -> skip;
BLOCK_COMMENT: '/*' .+? '*/' -> skip;
DOC_COMMENT: '/**' .+? '*/' -> skip;
